import IdealArithmetic.DedekindProject.CertifyRingOfIntegers.MaximalAPI
import IdealArithmetic.DedekindProject.CertifyRingOfIntegers.CertifyAdjoinRoot
import IdealArithmetic.DedekindProject.CertifyRingOfIntegers.CertificateDedekind
