import IdealArithmetic.DedekindProject.Polynomial.BrillhartIrreducibilityTest
import IdealArithmetic.DedekindProject.Polynomial.IrreduciblePolynomialZModp
import IdealArithmetic.DedekindProject.Polynomial.PolynomialsAsLists
