import IdealArithmetic.Examples.NF2_0_231_1.ClassGroupSaturated2_0_231_1_2
import IdealArithmetic.Examples.NF2_0_231_1.ClassGroupSaturated2_0_231_1_3
import IdealArithmetic.Examples.NF2_0_231_1.RelationIdeals2_0_231_1F0
import IdealArithmetic.Examples.NF2_0_231_1.PrimesBelowCert2_0_231_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with with α root of polynomial `X^2 - X + 58`.
Class group structure `[6, 2]`, generated by class of ideals `[(2, a + 1), (7, a + 3)]`. -/

/- Ring of integers with basis `[1, a]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible 

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

-- These instances were not needed previously. Additional in this new Lean/Mathlib version 
instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 2 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out 

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ []
  · fin_cases hc
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl



instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B 

-- Additional in this new Lean/Mathlib version 
instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O


def SturmRC : SturmBuilderOfList [[58, -1, 1], [-1, 2], [-231]] [58, -1, 1] [-1, 2] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic 
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [4]
  f := [1]
  epos := by decide
  fpos := by decide
  Q := [[-1, 2]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 1 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^2 - X + 58
  l := [58, -1, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[58, -1, 1], [-1, 2], [-231]]
  SB := SturmRC
  k := 0
  r := 1
  hr := by decide
  hreq := by decide 

def NPCU2 : pMaximalUnitsCertificateDvdT O 2 where 
 hp := by decide
 r := 0
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![]
 hu := by decide
 v := v
 m := 2
 hm := by norm_num
 hmv := v_pow_one
 t := 3
 hrle := by decide
 q := ![3, 5, 11]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat2.hq3
  | 1 => exact Sat2.hq5
  | 2 => exact Sat2.hq11
 I := ![Sat2.I0, Sat2.I1, Sat2.I2]
 hcard := fun i =>
  match i with  
  | 0 => Sat2.N0
  | 1 => Sat2.N1
  | 2 => Sat2.N2
 ζ := ![2, 2, 2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat2.R3) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat2.R5) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat2.R11) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 M := ![![1], ![0], ![1]]
 hM1 := by 
  intro i j hj
  fin_cases i <;> interval_cases j 
 hM2 := by 
  intro i 
  fin_cases i 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log20] ; decide
 Minv := ![![1]]
 hInv := by decide

def NPSU2 : pSaturatedClassGroupCertificateDvdT 2 ![J0, J1] ![6, 2] where 
 topMaximalUnitsCertificateDvdT := NPCU2
 a := ![alpha0,alpha1]
 γ := 2
 hc := by decide
 ψ := ![0, 1]
 iψ := ![0, 1] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow6
  | 1 => by convert J1_pow2
 N := ![![0, 0], ![0, 1], ![1, 1]]
 hM3 := by 
  intro (i : Fin 3) j
  match i , j with 
  | 0, 0 => exact Sat2.Log01
  | 0, 1 => exact Sat2.Log02
  | 1, 0 => exact Sat2.Log11
  | 1, 1 => exact Sat2.Log12
  | 2, 0 => exact Sat2.Log21
  | 2, 1 => exact Sat2.Log22
 hDl := by decide 
 NInv := ![![1, 0, 0], ![1, 1, 1], ![0, 1, 0]]
 hN := by decide 
def IC : Ideal O := Ideal.span (Set.range (fun i ↦ B.equivFun.symm (![![2, 0], ![0, 1]] i)))

def AIC: IdealEqSpanCertificate timesTableO IC
 ![![2, 0], ![0, 1]] 
 ![![2, 0], ![0, 1]] where
  T := Table 
  heq := timesTableT_eq_Table
  hieq := rfl 
  M :=![![![2, 0], ![0, 2]], ![![0, 1], ![-58, 1]]]
  hmulB := by decide
  f := ![![![1, 0], ![0, 0]], ![![0, 0], ![1, 0]]]
  g := ![![![1, 0], ![0, 2]], ![![0, 1], ![-29, 1]]]
  hle1 := by decide
  hle2 := by decide

 lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by 
  refine prime_not_dvd_torsion_of_not_dvd (by decide) IC 
     (ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate AIC))
     (by decide) (by decide)

def NPCU3 : pMaximalUnitsCertificateNDvdT O 3 where 
 hp := by decide
 r := 0
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![]
 hu := by decide
 t := 1
 hrle := by decide
 q := ![13]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat3.hq13
 I := ![Sat3.I0]
 hcard := fun i =>
  match i with  
  | 0 => Sat3.N0
 ζ := ![2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat3.R13) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion3
 M := ![![]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
 Minv := ![]
 hInv := by decide

def NPSU3 : pSaturatedClassGroupCertificateNDvdT 3 ![J0, J1] ![6, 2] where 
 topMaximalUnitsCertificateNDvdT := NPCU3
 a := ![alpha0,alpha1]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0, 0] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
  · convert true_imp_iff.2 ?_ 
    · decide
    · dsimp [alpha1]
      refine (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide) 
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow6
  | 1 => by convert J1_pow2
 N := ![![2]]
 hM2 := by 
  intro (i : Fin 1) j
  match i , j with 
  | 0, 0 => exact Sat3.Log00
 hDl := by decide 
 NInv := ![![2]]
 hN := by decide 

lemma T_discr : T.discr = -231 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = -231 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 1 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : MinkowskiBound K ≤ (9.685782846132922 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √231 ≤ 15.198694 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 1/2 * √231 ≤ 7.609347 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}


def e := ![6]
def s := ![4]
def g : (i : Fin 1) → Fin (e i) → Ideal O := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![I2N0, I2N1, I3N0, I5N0, I5N1, I7N0]

def BM : (i : Fin 1) → Fin (e i) → (Fin 2 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![5, 0], ![1, 0], ![3, 1], ![1, 1], ![5, 1], ![0, 1]]

lemma primesGenerationAux0  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 0)) => PB10.Il ((indexPair_inv s) ⟨0,x⟩))).flatten ↔ y ∈ List.ofFn (g 0) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I2N0, I2N1, I3N0, I3N0, I5N0, I5N1, I7N0, I7N0] ↔ y ∈ [I2N0, I2N1, I3N0, I5N0, I5N1, I7N0]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

  
lemma primesGenerationAux {x} : x ∈ (List.ofFn PB10.Il).flatten ↔ x ∈ List.ofFn (Fin.addCasesIter e g) := by
  refine (list_flatten_eq_list_addCasesIter g (s := s) PB10.Il ?_ x)
  rintro ⟨i, hi⟩ x
  interval_cases i 
  · exact primesGenerationAux0

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 10} ⊆ Set.range (Fin.addCasesIter e g) := 
  le_primes_below_bound_of_PrimesBelowBoundCertificate_le' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv ((Fin.addCasesIter e g)) PB10 (fun _ hx => primesGenerationAux.1 hx)

def g' : Fin 6 → nonZeroDivisors (Ideal O) := by
  intro i
  have : (Fin.addCasesIter e g) i ∈ (List.ofFn PB10.Il).flatten := by 
    simp only [primesGenerationAux, List.mem_ofFn, exists_apply_eq_apply]
  exact Ideal.toNonZeroDivisorOfNeZero ((Fin.addCasesIter e g) i) 
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate' _ PB10) (hc ▸ this) ))

def x : Fin 2 → Ideal O := ![J0,J1] 

def x' :  Fin 2 → nonZeroDivisors (Ideal O) := by 
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (x i) (?_ )
  unfold x
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![6, 2] i) (by fin_cases i <;> decide) , NPSU2.h] 
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU2]
  fin_cases i    
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 
  · dsimp [alpha1] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma g'_apply : ∀ (i : Fin 6), ↑(g' i) = (Fin.addCasesIter e g) i := by
  intro i
  rfl

lemma x'_apply : ∀ (i : Fin 2), ↑(x' i) = x i := by
  intro i
  rfl 
  
lemma relations_proof0 (i : Fin 6) : IsInClass O x (g 0 i) (BM 0 i) := by
  show IsInClass O x (g 0 i) (![![5, 0], ![1, 0], ![3, 1], ![1, 1], ![5, 1], ![0, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N0))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N0))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N0))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R7N0))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      g'_apply x'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop g BM (IsInClass O x) ?_
    rintro ⟨i, hi⟩
    interval_cases i 
    · exact relations_proof0

def ClassGroupO_equiv : (∀ i : Fin 2 , (ZMod (![6, 2] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 2), NeZero (![6, 2] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate x'_apply NPSU2.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![6, 2] i = ∏ i, (![2, 3] i) ^ (![2, 1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [2, 3] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![2, 3]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩ 
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases 
  by_cases h : p = 2
  simp_rw [h] ; left
  exact NPSU2 
  by_cases h : p = 3
  simp_rw [h] ; right
  exact NPSU3 
  omega 
 
def class_group_equiv : (∀ i : Fin 2 , (ZMod (![6, 2] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_12 : NumberField.classNumber K = 12 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide 
