import Mathlib.NumberTheory.SmoothNumbers
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import IdealArithmetic.Saturation.ClassGroupSaturation
import IdealArithmetic.Generation.FinAddCasesIter

/-!
# Certificates for generators of the class group

We define a factor base bound and define structures that collect and certify the prime ideals
of norm below a certain bound. We also provide results to reduce the set of generators of a
commutative group based on relations.

## Main definition
- `isFactorBaseBound`: the class group of a number field is generated by prime ideals of norm below
  this bound.
- `PrimesBelowBoundCertificate` : certifies the ideals of norm below certain bound.
- `PrimesBelowBoundCertificateInterval`: certifies the ideals above primes in a some interval and
  of norm below certain bound.

## Main results
- `subgroup_closure_eq_classGroup'`: reduce the set of generators of the class group by giving
  relations with prime ideals below a factor base bound.
- `le_primes_below_bound_of_PrimesBelowBoundCertificate'`: proves that
  `PrimesBelowBoundCertificate` contains the prime ideals below a certain bound. -/


open NumberField

/-- The Minkowski bound for number fields. -/
noncomputable def MinkowskiBound (K : Type*) [Field K] [NumberField K] : ℝ :=
  (4 / Real.pi) ^ InfinitePlace.nrComplexPlaces K *
  (↑(Module.finrank ℚ K).factorial / ↑(Module.finrank ℚ K) ^ Module.finrank ℚ K * √|↑(discr K)|)

/-- An upper bound on the Minkowski bound given an upper bound of a decimal approximation. -/
theorem K_minkowski_decimal {F : Type*} [Field F] [NumberField F] (r : ℝ)
    (h : (4 / 3.14159265358979323846 : ℝ) ^ InfinitePlace.nrComplexPlaces F
      * (↑(Module.finrank ℚ F).factorial / ↑(Module.finrank ℚ F)
        ^ Module.finrank ℚ F * √|↑(NumberField.discr F)|) ≤ r) :
    MinkowskiBound F ≤ r  := by
  unfold MinkowskiBound
  have := Real.pi_gt_d20
  have : (4 / Real.pi) ^ (NumberField.InfinitePlace.nrComplexPlaces F) ≤
    (4 / 3.14159265358979323846) ^ (NumberField.InfinitePlace.nrComplexPlaces F) := by
    refine pow_le_pow_left₀ ?_ ?_ _
    · refine div_nonneg (by norm_num) (by exact Real.pi_nonneg)
    · refine le_of_lt ?_
      refine div_lt_div_of_pos_left (by norm_num) (by norm_num) this
  refine le_trans ?_ h
  refine mul_le_mul_of_nonneg_right this ?_
  refine mul_nonneg ?_ ?_
  · refine div_nonneg ?_ ?_
    · simp only [Nat.cast_nonneg]
    · simp only [Nat.cast_nonneg, pow_nonneg]
  · simp only [Real.sqrt_nonneg]


/-- A real number `T` is a bound for a factor base if
the class group of a number field is generated by the prime ideals of norm below that bound.

An example is the `MinkowskiBound`. However, if one assumes GRH, asymptotically better
bounds exist.  -/
def isFactorBaseBound (K : Type*) [Field K] [NumberField K] (T : ℝ) :=
  Subgroup.closure
  (ClassGroup.mk0 '' {I : ↥(nonZeroDivisors (Ideal (RingOfIntegers K)))
    | (I : Ideal (RingOfIntegers K)).IsPrime ∧
      Ideal.absNorm (I : Ideal (RingOfIntegers K)) ≤ T }) = ⊤

/-- The Minkowski Bound is a factor base bound. -/
lemma MinkowskiBound_isFactorBaseBound (K : Type*) [Field K] [NumberField K] :
    isFactorBaseBound K (MinkowskiBound K) := by
  refine le_antisymm (le_top) ?_
  intro C hC
  obtain ⟨J , hJC, hJnorm⟩ := exists_ideal_in_class_of_norm_le C
  have hJp := prod_normalizedFactors_eq_self (nonZeroDivisors.coe_ne_zero J)
  have hJn := Ideal.absNorm_pos_iff_mem_nonZeroDivisors.2 J.2
  have hPf : ∀ p, p ∈ UniqueFactorizationMonoid.normalizedFactors
    (↑J : Ideal (RingOfIntegers K)) → p.IsPrime ∧ J ≤ p :=
  fun p hp => (Ideal.mem_normalizedFactors_iff (nonZeroDivisors.coe_ne_zero J)).1 hp
  have aux1 : ∀ p, p ∈ UniqueFactorizationMonoid.normalizedFactors (↑J : Ideal (RingOfIntegers K)) →
  p.absNorm ∣ (J : Ideal (RingOfIntegers K)).absNorm := by
    intro p hp
    exact (Ideal.absNorm_dvd_absNorm_of_le (hPf p hp).2)
  have aux2 : ∀ p, p ∈ UniqueFactorizationMonoid.normalizedFactors
    (↑J : Ideal (RingOfIntegers K)) → p ∈ nonZeroDivisors (Ideal (RingOfIntegers K)) := by
    intro p hp
    rw [← Ideal.absNorm_ne_zero_iff_mem_nonZeroDivisors]
    by_contra hc
    simp_rw [zero_dvd_iff.1 (hc ▸ aux1 p hp )] at hJn
    contradiction
  let M := List.pmap (fun p hp => (⟨p, aux2 _ hp⟩ :
    nonZeroDivisors (Ideal (RingOfIntegers K))))
    (UniqueFactorizationMonoid.normalizedFactors
    (↑J : Ideal (RingOfIntegers K))).toList (by simp)
  have hMs : List.map Subtype.val M = (UniqueFactorizationMonoid.normalizedFactors
    (↑J : Ideal (RingOfIntegers K))).toList := by
    simp only [List.pmap_eq_attachWith, mem_nonZeroDivisors_iff_ne_zero, Submodule.zero_eq_bot,
      ne_eq, List.map_subtype, List.unattach_attachWith, List.map_id_fun', id_eq, M]
  have hMprod : (Multiset.ofList M).prod = J := by
    rw [← Subtype.val_inj, ← hJp, Multiset.prod_coe, SubmonoidClass.coe_list_prod, hMs,
    Multiset.prod_toList]
  apply_fun (ClassGroup.mk0) at hMprod
  rw [map_multiset_prod, hJC ] at hMprod
  rw [← hMprod]
  refine Submonoid.multiset_prod_mem _  _ ?_
  intro P hP
  refine Subgroup.subset_closure ?_
  obtain ⟨p, hp1, hp2⟩ := Multiset.mem_map.1 hP
  simp only [List.pmap_eq_attachWith, Multiset.mem_coe, List.mem_attachWith,
    Multiset.mem_toList, M] at hp1
  simp only [Set.mem_image, Set.mem_setOf_eq, Subtype.exists, mem_nonZeroDivisors_iff_ne_zero,
  exists_and_left]
  use (p : Ideal (RingOfIntegers K))
  constructor
  · constructor
    · exact (hPf _ hp1).1
    · have aux3 := Nat.le_of_dvd (hJn) (aux1 _ hp1)
      rify at aux3
      refine le_trans (aux3) hJnorm
  · have : (p : Ideal (RingOfIntegers K)) ≠ 0 := by
      rw [← mem_nonZeroDivisors_iff_ne_zero]
      simp only [SetLike.coe_mem]
    use this

variable {K : Type*} [Field K] [NumberField K]

local notation "Oκ" => RingOfIntegers K



/-- The set of ideals of norm below `B` equals the union of the sets of ideals above `p`
with norm less than `B`, where `p` ranges over the prime numbers. -/
lemma primes_below_bound_of_factorization' (B : ℕ)
    (F : Nat.primesBelow B → Multiset (Ideal Oκ))
    (hP : ∀ p, ∀ q ∈ (F p), q.IsPrime)
    (hnz : ∀ p, ∀ q ∈ (F p), q ≠ ⊥)
    (hPpord : ∀ p, (F p).prod ≤ Ideal.span {↑p}) :
    {I : Ideal Oκ | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < B} =
      ⋃ (p : Nat.primesBelow B), {q ∈ F p | q.absNorm < B} := by
  refine le_antisymm ?_ ?_
  · intro I hIn
    rcases hIn with ⟨hIn1, hIn2, hIn3 ⟩
    let P := Ideal.under ℤ I
    have hPP: P.IsPrime :=  Ideal.IsPrime.under ℤ P
    let p := Submodule.IsPrincipal.generator P
    have hPeq : P = Ideal.span {p} := (Ideal.span_singleton_generator _ ).symm
    have : I.LiesOver (Ideal.span {p}) := by
      rw [← hPeq]
      simp only [Ideal.over_under, P]
    have hpn : p ≠ 0 := by
      intro hc
      erw [hc, Ideal.span_zero] at this
      have hIaux : I ∈ (⊥ : Ideal ℤ).primesOver Oκ := by
        exact ⟨hIn2, this ⟩
      rw [Ideal.primesOver_bot] at hIaux
      simp only [Set.mem_singleton_iff] at hIaux
      rw [hIaux] at hIn1
      simp only [Ideal.absNorm_bot, lt_self_iff_false] at hIn1
    have hpp : Prime p := by
      rw [← Ideal.span_singleton_prime, ← (Ideal.span_singleton_generator _ ).symm]
      exact hPP
      · exact hpn
    haveI hpM : Ideal.IsMaximal (Ideal.span {p} ):= by
      rw [← hPeq]
      refine IsPrime.to_maximal_ideal ?_
      rw [hPeq]
      simp only [ne_eq, Ideal.span_singleton_eq_bot, hpn, not_false_eq_true]
    simp only [Set.mem_iUnion,  Subtype.exists]
    use p.natAbs
    have hlB : p.natAbs < B := by
      rw [Ideal.absNorm_eq_pow_inertiaDeg I hpp] at hIn3
      refine lt_of_le_of_lt ?_ hIn3
      nth_rw 1 [← pow_one (p.natAbs)]
      refine Nat.pow_le_pow_of_le ?_ ?_
      · exact Nat.Prime.one_lt (Int.prime_iff_natAbs_prime.1 hpp)
      · exact (Ideal.inertiaDeg_pos (Ideal.span {p}) I)
    have hBm : p.natAbs ∈ B.primesBelow := by
      rw [Nat.mem_primesBelow]
      exact ⟨hlB, Int.prime_iff_natAbs_prime.1 hpp⟩
    use hBm
    constructor
    · have hprod : (F ⟨p.natAbs, hBm⟩).prod ≤ I := by
        refine le_trans (hPpord ⟨p.natAbs, hBm⟩) ?_
        rw [Ideal.span_singleton_le_iff_mem]
        convert (Ideal.mem_of_liesOver I (Ideal.span {p}) ↑p.natAbs).1 ?_
        exact Eq.symm (algebraMap.coe_natCast p.natAbs)
        simp only [Int.natCast_natAbs, abs_mem_iff]
        exact Ideal.mem_span_singleton_self p
      obtain ⟨J, hJ1, hJ2⟩ := (Ideal.IsPrime.multiset_prod_le hIn2).1 hprod
      have hJp : J.IsPrime := hP _ J hJ1
      rw [Ring.DimensionLeOne.prime_le_prime_iff_eq ?_] at hJ2
      rw [← hJ2]
      exact hJ1
      · grind
    · exact hIn3
  · intro I hI
    simp only [Set.mem_iUnion] at hI
    obtain ⟨p, hp1, hp2⟩ := hI
    constructor
    · refine Nat.pos_of_ne_zero ?_
      intro hc
      rw [Ideal.absNorm_eq_zero_iff] at hc
      grind
    · exact ⟨hP _ _ hp1,  hp2⟩

/-- The set of ideals of norm below `B` equals the union of the sets of ideals above `p`
with norm less than `B`, where `p` ranges over the prime numbers. -/
lemma primes_below_bound_of_factorization (B : ℕ)
    (F : Nat.primesBelow B → Multiset (Ideal Oκ))
    (hP : ∀ p, ∀ q ∈ (F p), q.IsPrime)
    (hPprod : ∀ p, (F p).prod = Ideal.span {↑p} ) :
    {I : Ideal Oκ | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < B} =
      ⋃ (p : Nat.primesBelow B), {q ∈ F p | q.absNorm < B} := by
  refine primes_below_bound_of_factorization' B F hP ?_ ?_
  · intro p hq hqmem hqz
    rw [hqz] at hqmem
    have : (Ideal.span {↑p} : Ideal Oκ) = 0 := by
      rw [← hPprod p]
      refine Multiset.prod_eq_zero ?_
      exact hqmem
    simp only [Submodule.zero_eq_bot, Ideal.span_singleton_eq_bot, Nat.cast_eq_zero] at this
    exact Nat.Prime.ne_zero (Nat.mem_primesBelow.1 p.2).2 this
  · intro p
    rw [hPprod p]


-- NOTE: Even though we could use the to_additive attribute in the multiplicative version,
-- proving the additive version first is easier.

-- Why use Fn tuples instead of lists? Because its better to use the linear algebra library,
-- where vectors and encoded in such a way.
section

lemma addSubgroup_closure_le_of_invertible_relation {G R : Type*} {m n r : Type}
    [hn : Fintype n] [hm : Fintype m] [Fintype r] [DecidableEq m]
    [AddCommMonoid G] [CommRing R] [Module R G]  {g : m → G} {x : n → G} {A : Matrix r m R}
    {B : Matrix r n R} (hA : ∃ M : Matrix m r R, M * A = 1)
    (hg : ∀ i, ∑ j , (A i j) • (g j) = ∑ j , (B i j) • (x j)) :
      Submodule.span R (Set.range g) ≤ Submodule.span R (Set.range x) := by
  rw [Submodule.span_le]
  intro t ht
  obtain ⟨i, hi⟩  := Set.mem_range.1 ht
  rw [← hi]
  obtain ⟨M, hM⟩ := hA
  have : ∀ t , ∀ h : Fintype t, ∀ S : Matrix r t R , ∀ g : t → G ,
    (∀ i , ∑ k, (M i k) • (∑ j, (S k j) • (g j)) = ∑ k, ((M * S) i k) • (g k)) := by
    intro t ht S g i
    simp_rw [Matrix.mul_apply]
    simp_rw [Finset.smul_sum, Finset.sum_smul, ← smul_assoc]
    rw [Finset.sum_comm]
    rfl
  have auxM := this m hm A g i
  have auxB := this n hn B x
  simp_rw [hg] at auxM
  rw [hM, auxB i] at auxM
  simp only [Matrix.one_apply, ite_smul, one_smul, zero_smul, Finset.sum_ite_eq, Finset.mem_univ,
    ↓reduceIte] at auxM
  rw [← auxM]
  apply Submodule.sum_mem
  intro c hc
  refine Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_range_self c))

/-- We can reduce the number of generators of a additive commutative group
  given some relations between them. Additive version of
  `subgroup_closure_eq_of_invertible_relation`. -/
lemma addSubgroup_closure_le_of_invertible_relation' {G : Type*} {m n r : Type}
    [hn : Fintype n] [hm : Fintype m] [Fintype r] [DecidableEq m]
    [AddCommGroup G] {g : m → G} {x : n → G} {A : Matrix r m ℤ} {B : Matrix r n ℤ}
    (hA : ∃ M : Matrix m r ℤ, M * A = 1)
    (hg : ∀ i, ∑ j , (A i j) • (g j) = ∑ j , (B i j) • (x j))
    (hs : ∀ i, x i ∈ AddSubgroup.closure (Set.range g)) :
      AddSubgroup.closure (Set.range x) = AddSubgroup.closure (Set.range g) := by
  rw [← Submodule.span_int_eq_addSubgroupClosure, ← Submodule.span_int_eq_addSubgroupClosure]
  refine le_antisymm ?_ ?_
  · erw [Submodule.span_le]
    intro t ht
    obtain ⟨i, hi⟩ := Set.mem_range.1 ht
    specialize hs i
    rw [← Submodule.span_int_eq_addSubgroupClosure] at hs
    rw [← hi]
    exact hs
  · exact addSubgroup_closure_le_of_invertible_relation hA hg

lemma subgroup_closure_le_of_invertible_relation {G : Type*} {m n r : Type}
  [hn : Fintype n] [hm : Fintype m] [Fintype r] [DecidableEq m]
  [CommGroup G] {g : m → G} {x : n → G} {A : Matrix r m ℤ} {B : Matrix r n ℤ}
  (hA : ∃ M : Matrix m r ℤ, M * A = 1)
  (hg : ∀ i, ∏ j , (g j) ^ (A i j) = ∏ j, (x j) ^ (B i j)) :
    Subgroup.closure (Set.range g) ≤ Subgroup.closure (Set.range x) := by
  apply_fun Subgroup.toAddSubgroup
  rw [Subgroup.toAddSubgroup_closure, Subgroup.toAddSubgroup_closure]
  rw [← Equiv.image_symm_eq_preimage, ← Equiv.image_symm_eq_preimage,
    ← Set.range_comp, ← Set.range_comp]
  rw [← Submodule.span_int_eq_addSubgroupClosure, ← Submodule.span_int_eq_addSubgroupClosure]
  refine addSubgroup_closure_le_of_invertible_relation hA hg

/-- We can reduce the number of generators of a multiplicative commutative group
  given some relations between them. Multiplicative version of
  `addSubgroup_closure_le_of_invertible_relation'`-/
lemma subgroup_closure_eq_of_invertible_relation {G : Type*} {m n r : Type}
  [hn : Fintype n] [hm : Fintype m] [Fintype r] [DecidableEq m]
  [CommGroup G] {g : m → G} {x : n → G} {A : Matrix r m ℤ} {B : Matrix r n ℤ}
  (hA : ∃ M : Matrix m r ℤ, M * A = 1)
  (hg : ∀ i, ∏ j , (g j) ^ (A i j) = ∏ j, (x j) ^ (B i j))
  (hs : ∀ i, x i ∈ Subgroup.closure (Set.range g)) :
    Subgroup.closure (Set.range x) = Subgroup.closure (Set.range g) := by
  refine le_antisymm ?_ ?_
  · rw [Subgroup.closure_le]
    intro t ht
    obtain ⟨i, hi⟩ := Set.mem_range.1 ht
    rw [← hi]
    exact hs i
  · exact subgroup_closure_le_of_invertible_relation hA hg

-- Note: I prefer to use less than in the bound, because I can use the primes less than type.

lemma subgroup_closure_eq_classGroup_of_bound {m n r : Type} {D : ℝ} {b : ℕ}
    [hn : Fintype n] [hm : Fintype m] [Fintype r] [DecidableEq m]
    {g : m → Ideal Oκ} {g' : m → nonZeroDivisors (Ideal (Oκ))}
    {x : n → Ideal Oκ} {x' : n → nonZeroDivisors (Ideal (Oκ))}
    (hg' : ∀ i, ↑(g' i) = g i) (hx' : ∀ i, ↑(x' i) = x i)
    (hbg : isFactorBaseBound K D) (hB : D < b)
    (hg : {I : Ideal Oκ | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < b} ⊆ Set.range g)
    {A : Matrix r m ℕ} {B : Matrix r n ℕ}
    (hA : ∃ M : Matrix m r ℤ, M * A.map (algebraMap ℕ ℤ) = 1)
    (hgmul : ∀ i, ∃ (α β : Oκ), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
      Ideal.span {α} * ∏ j , (g j) ^ (A i j) = Ideal.span {β} * ∏ j, (x j) ^ (B i j)) :
      Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  have hgnz : ∀ i , g i ∈ nonZeroDivisors (Ideal Oκ) := by
        intro i
        rw [← (hg' i )]
        exact SetLike.coe_mem _
  have aux1 : ClassGroup.mk0 '' {I : ↥(nonZeroDivisors (Ideal (Oκ))) | (I : Ideal Oκ).IsPrime ∧
    Ideal.absNorm (I : Ideal Oκ) < b } ⊆ Set.range (fun i => ClassGroup.mk0 (g' i)) := by
      intro x
      simp only [Set.mem_image, Set.mem_setOf_eq, Subtype.exists,
         exists_and_left, Set.mem_range, forall_exists_index, and_imp]
      intro I hIp hIn hIz hIc
      have hmem : I ∈ Set.range g := by
        suffices h : I ∈ {I | 0 < Ideal.absNorm I ∧ I.IsPrime ∧ Ideal.absNorm I < b} from (hg h)
        constructor
        · exact Ideal.absNorm_pos_iff_mem_nonZeroDivisors.2 hIz
        · exact ⟨hIp, hIn⟩
      obtain ⟨y, hy⟩ :=  Set.mem_range.1 hmem
      use y
      simp_rw [← hIc, ← hy, ← hg']
  have htop: ⊤ = Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (g' i))) := by
    refine le_antisymm ?_ ?_
    · unfold isFactorBaseBound at hbg
      rw [← hbg]
      refine Subgroup.closure_mono (le_trans (Set.image_mono ?_) aux1)
      intro I hIp
      refine ⟨hIp.1, ?_ ⟩
      rify
      refine lt_of_le_of_lt hIp.2 hB
    · exact le_top
  rw [htop]
  refine subgroup_closure_eq_of_invertible_relation (A := A.map (algebraMap ℕ ℤ))
    (B := B.map (algebraMap ℕ ℤ)) hA ?_ ?_
  · intro i
    simp only [Matrix.map_apply, eq_natCast, zpow_natCast]
    simp_rw [← map_pow, ← map_prod, ClassGroup.mk0_eq_mk0_iff]
    convert hgmul i
    · simp only [SubmonoidClass.coe_finset_prod, SubmonoidClass.coe_pow, hg']
    · simp only [SubmonoidClass.coe_finset_prod, SubmonoidClass.coe_pow, hx']
  · rw [← htop]
    simp only [Subgroup.mem_top, implies_true]

/-- Given collections of nonzero ideals `g` and `x` of `Oκ`, if `g` contains
  all prime ideals of norm below a factor base bound,
  and we have `⟨α⟩ * gᵢ = ⟨β⟩ * ∏ (xⱼ) ^ Bᵢⱼ`, then the class group is generated by the
  image of `x`. -/
lemma subgroup_closure_eq_classGroup_bound' {m n : Type} {D : ℝ} {b : ℕ}
    [hn : Fintype n] [hm : Fintype m] [DecidableEq m]
    {g : m → Ideal Oκ} {g' : m → nonZeroDivisors (Ideal (Oκ))}
    {x : n → Ideal Oκ} {x' : n → nonZeroDivisors (Ideal (Oκ))}
    (hg' : ∀ i, ↑(g' i) = g i) (hx' : ∀ i, ↑(x' i) = x i)
    (hbg : isFactorBaseBound K D) (hB : D < b)
    (hg : {I : Ideal Oκ | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < b} ⊆ Set.range g)
    (B : Matrix m n ℕ) (hgmul : ∀ i, ∃ (α β : Oκ), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
      Ideal.span {α} * (g i) = Ideal.span {β} * ∏ j, (x j) ^ (B i j)) :
      Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup_of_bound hg' hx' hbg hB hg (A := 1) (B := B) ?_ ?_
  · use 1
    simp only [eq_natCast, CharP.cast_eq_zero, Nat.cast_one, Matrix.map_one, mul_one]
  · intro i
    obtain ⟨α, β, hα, hβ, hp ⟩ :=  hgmul i
    use α , β , hα, hβ
    rw [← hp]
    congr
    rw [Finset.prod_eq_single (M := Ideal Oκ) i ?_ ?_, Matrix.one_apply]
    simp only [↓reduceIte, pow_one]
    · intro b hb hbn
      simp only [Matrix.one_apply, pow_ite, pow_one, pow_zero, Ideal.one_eq_top, ite_eq_right_iff]
      intro hc
      exfalso
      exact hbn hc.symm
    · simp only [Finset.mem_univ, not_true_eq_false, Matrix.one_apply_eq, pow_one,
      Ideal.one_eq_top, IsEmpty.forall_iff]


lemma primes_below_bound_of_equiv {m} {R S : Type*} [CommRing R] [CommRing S]
    (φ : R ≃+* S) {g : m → Ideal R} (b : ℕ)
    (h : {I : Ideal S | 0 < Nat.card (S ⧸ I) ∧ I.IsPrime ∧ Nat.card (S ⧸ I) < b} ⊆
      Set.range (Ideal.map φ ∘ g)) :
    {I : Ideal R | 0 < Nat.card (R ⧸ I) ∧ I.IsPrime ∧ Nat.card (R ⧸ I) < b} ⊆ Set.range g := by
  rintro I hImem
  have hcard : ∀ (J : Ideal R), Nat.card (R ⧸ I) = Nat.card (S ⧸ (I.map φ)) := by
    intro J
    refine Nat.card_congr ?_
    exact (Ideal.quotientEquiv I (I.map φ) φ rfl).toEquiv
  have hprime : ∀ (J : Ideal R) , J.IsPrime ↔ (J.map φ).IsPrime := by
    intro J
    constructor
    · intro hx ; exact Ideal.map_isPrime_of_equiv φ
    · intro hx
      convert Ideal.map_isPrime_of_equiv φ.symm (I := (Ideal.map φ J))
      erw [Ideal.map_of_equiv]
  have : I.map φ ∈ Set.range (Ideal.map φ ∘ g) := by
    apply h
    dsimp
    rw [← hcard I , ← hprime I]
    exact hImem
  suffices haux : Ideal.map φ.symm (Ideal.map φ I) ∈ (Ideal.map φ.symm)'' (Set.range (Ideal.map φ ∘ g)) by
    erw [← Set.range_comp, Ideal.map_of_equiv] at haux
    convert haux
    ext i
    simp only [Function.comp_apply, Ideal.map_symm, Ideal.mem_comap, Ideal.apply_mem_of_equiv_iff]
  exact Set.mem_image_of_mem (Ideal.map φ.symm) this


/-- Version of `subgroup_closure_eq_classGroup_bound'` over a ring `S` isomorphic to `Oκ`.This
  gives flexibility on the representation of `Oκ`, which is especially useful if we have a
  computational model for it which is not definitionally equal. -/
lemma subgroup_closure_eq_classGroup' {m n : Type} {D : ℝ} {b : ℕ}
    [hn : Fintype n] [hm : Fintype m] [DecidableEq m] {S : Type*}
    [CommRing S] [Nontrivial S] [IsDedekindDomain S] [Module.Free ℤ S]
    ( φ : S ≃+* Oκ)
    {g : m → Ideal S} {g' : m → nonZeroDivisors (Ideal (S))}
    {x : n → Ideal S} {x' : n → nonZeroDivisors (Ideal (S))}
    (hg' : ∀ i, ↑(g' i) = g i) (hx' : ∀ i, ↑(x' i) = x i)
    (hbg : isFactorBaseBound K D) (hB : D < b)
    (hg : {I : Ideal S | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < b} ⊆ Set.range g)
    (B : Matrix m n ℕ) (hgmul : ∀ i, ∃ (α β : S), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
      Ideal.span {α} * (g i) = Ideal.span {β} * ∏ j, (x j) ^ (B i j)) :
      Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  --No need to assume equality of subalgebras.
  let gg : m → Ideal Oκ := fun i => Ideal.map φ (g i)
  let xx : n → Ideal Oκ := fun i => Ideal.map φ (x i)
  have hgaux : ∀ i, (g' i).val ≠ ⊥ := fun i => nonZeroDivisors.ne_zero (g' i).2
  have hxaux : ∀ i, (x' i).val ≠ ⊥ := fun i => nonZeroDivisors.ne_zero (x' i).2
  have hgg: ∀ i, Ideal.map φ (g' i).val ∈ nonZeroDivisors (Ideal Oκ) := by
    intro i
    rw [mem_nonZeroDivisors_iff_ne_zero (M₀ := Ideal Oκ), Submodule.zero_eq_bot, ne_eq, Ideal.map_eq_bot_iff_le_ker, RingHom.ker_equiv, le_bot_iff]
    exact hgaux i
  have hxx: ∀ i, Ideal.map φ (x' i).val ∈ nonZeroDivisors (Ideal Oκ) := by
    intro i
    rw [mem_nonZeroDivisors_iff_ne_zero (M₀ := Ideal Oκ), Submodule.zero_eq_bot, ne_eq, Ideal.map_eq_bot_iff_le_ker, RingHom.ker_equiv, le_bot_iff]
    exact hxaux i
  let gg' : m → nonZeroDivisors (Ideal Oκ) := fun i => ⟨Ideal.map φ (g' i).val, hgg i⟩
  let xx' : n → nonZeroDivisors (Ideal Oκ) := fun i => ⟨Ideal.map φ (x' i).val, hxx i⟩
  have : IsDedekindDomain ↥(integralClosure ℤ K) := by
    show IsDedekindDomain Oκ
    exact NumberField.RingOfIntegers.instIsDedekindDomain K
  let E : ClassGroup S ≃* ClassGroup Oκ := ClassGroup.congr φ
  apply_fun (Subgroup.map (G := ClassGroup S) (N := ClassGroup Oκ) E)
  · rw [Subgroup.map_top_of_surjective _ (by exact EquivLike.surjective E)]
    rw [MonoidHom.map_closure]
    convert subgroup_closure_eq_classGroup_bound' (K := K) (m := m) (n := n)
       (b := b) (g := gg) (x := xx) (g' := gg') (x' := xx') ?_ ?_ hbg hB ?_ B ?_
    · rw [← Set.range_comp]
      refine (congr_arg _ ?_)
      ext i
      simp only [ClassGroup.congr, MonoidHom.coe_coe, Function.comp_apply, E]
      apply ClassGroup.map_apply'
      rfl
    · intro i
      simp only [hg', gg, gg']
    · intro i
      simp only [hx', xx, xx']
    · convert primes_below_bound_of_equiv φ.symm (g := gg) b ?_
      · rw [Ideal.absNorm_apply, Submodule.cardQuot_apply]
      · rw [Ideal.absNorm_apply, Submodule.cardQuot_apply]
      convert hg
      · rw [Ideal.absNorm_apply, Submodule.cardQuot_apply]
      · rw [Ideal.absNorm_apply, Submodule.cardQuot_apply]
      ext i
      simp only [Function.comp_apply, Ideal.map_symm, Ideal.mem_comap, Ideal.apply_mem_of_equiv_iff,
        gg]
    · intro i
      obtain ⟨α, β, hα, hβ, hαβ⟩ := hgmul i
      use (φ α), φ β, (EmbeddingLike.map_ne_zero_iff.mpr hα) ,(EmbeddingLike.map_ne_zero_iff.mpr hβ)
      simp [gg, xx]
      apply_fun (Ideal.map φ) at hαβ
      simp only [Ideal.map_mul, Ideal.map_span, Set.image_singleton] at hαβ
      convert hαβ
      let φaux := Ideal.mapHom φ
      have hIaux : ∀ I , Ideal.map φ I = φaux I := by
        intro I
        rfl
      simp_rw [hIaux, ← map_pow]
      rw [map_prod]
  · refine Subgroup.map_injective (EquivLike.injective E)


/-- A version of `subgroup_closure_eq_classGroup'` using the Minkowski bound-/
lemma subgroup_closure_eq_classGroup'' {m n : Type} {b : ℕ}
    [hn : Fintype n] [hm : Fintype m] [DecidableEq m]
    {S : Type*} [CommRing S] [Nontrivial S] [IsDedekindDomain S] [Module.Free ℤ S]
    ( φ : S ≃+* Oκ)
    {g : m → Ideal S} {g' : m → nonZeroDivisors (Ideal (S))}
    {x : n → Ideal S} {x' : n → nonZeroDivisors (Ideal (S))}
    (hg' : ∀ i, ↑(g' i) = g i) (hx' : ∀ i, ↑(x' i) = x i)
    (hB : MinkowskiBound K < b)
    (hg : {I : Ideal S | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < b} ⊆ Set.range g)
    (B : Matrix m n ℕ) (hgmul : ∀ i, ∃ (α β : S), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
      Ideal.span {α} * (g i) = Ideal.span {β} * ∏ j, (x j) ^ (B i j)) :
      Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup' (D := MinkowskiBound K) φ hg' hx' ?_ hB hg B hgmul
  exact MinkowskiBound_isFactorBaseBound K

end


----------------------------------------------------------------------------------

section CertificateBound

/- Note: How should I store the prime ideal info?
It's better (modular) to do it locally for every prime and then put it together.
Lists have the flatten function which is useful, but after some back in forth I think it is better
to use Fn tuples because it allows for easier indexing (fixed length, no bound side conditions),
especially when splitting into intervals. -/

/-- This predicate states that a given tuple of ideals is the factorization of the
  ideal `pS`.  -/
structure IsPrimesAboveP {S : Type*} [CommRing S] (p : ℕ) {g : ℕ} (F : Fin g → Ideal S) where
  Ip : ∀ i, (F i).IsPrime
  hPprod : ∏ i, F i = Ideal.span {↑p}

/-- This predicate states that a given tuple (assuming it does not contain zero)
  of ideals contains the primes above the ideal `pS`.  -/
structure ContainsPrimesAboveP {S : Type*} [CommRing S] (p : ℕ) {g : ℕ} (F : Fin g → Ideal S) where
  Ip : ∀ i, (F i).IsPrime
  hPprod : ∏ i, F i ≤ Ideal.span {↑p}
  --hnZ : ∀ i, F i ≠ ⊥


-- pattern matching with large n is annoying?

/-- Certificate for the ideals of norm below a bound `B`. -/
structure PrimesBelowBoundCertificate (S : Type*) [CommRing S] [Nontrivial S] (B : ℕ) where
  /-- The number of prime numbers below `B`. -/
  m : ℕ
  /-- A tuple of arities, where `g i` is the number of prime ideals (with multiplicity) above `pO`-/
  g : Fin m → ℕ
  /-- The tuple of prime numbers below `B`-/
  P : Fin m → ℕ
  hP : Set.range P = Nat.primesBelow B
  /-- Factorization tuples for the ideals `i`-th prime number in `O`-/
  I : Π i,  Fin (g i) → (Ideal S)
  hC : ∀ i : Fin m, IsPrimesAboveP (P i) (I i)
  /-- Norms corresponding to the factorization of the `i`-th prime in `O`.-/
  N :  Π i,  Fin (g i) → ℕ
  hN : ∀ i, ∀ j, Nat.card (S ⧸ I i j) = N i j
  /-- Lists of ideals over the `i`-th prime, with norm less than `B`-/
  Il : Fin m → List (Ideal S)
  hIl : ∀ i, List.map (Prod.fst) (List.filter (λ p => p.2 < B)
    (List.zip (List.ofFn (I i)) (List.ofFn (N i)))) = Il i

/-- Certificate for the ideals of norm below a bound `B`. -/
structure PrimesBelowBoundCertificate' (S : Type*) [CommRing S] [Nontrivial S] (B : ℕ) where
  /-- The number of prime numbers below `B`. -/
  m : ℕ
  /-- A tuple of arities, where `g i` is the number of prime ideals (with multiplicity) above `pO`-/
  g : Fin m → ℕ
  /-- The tuple of prime numbers below `B`-/
  P : Fin m → ℕ
  hP : Set.range P = Nat.primesBelow B
  /-- Factorization tuples for the ideals `i`-th prime number in `O`-/
  I : Π i,  Fin (g i) → (Ideal S)
  hC : ∀ i : Fin m, ContainsPrimesAboveP (P i) (I i)
  /-- Norms corresponding to the factorization of the `i`-th prime in `O`.-/
  N :  Π i,  Fin (g i) → ℕ
  hNz : ∀ i, ∀ j , N i j ≠ 0
  hN : ∀ i, ∀ j, Nat.card (S ⧸ I i j) = N i j
  /-- Lists of ideals over the `i`-th prime, with norm less than `B`-/
  Il : Fin m → List (Ideal S)
  hIl : ∀ i, List.map (Prod.fst) (List.filter (λ p => p.2 < B)
    (List.zip (List.ofFn (I i)) (List.ofFn (N i)))) = Il i


-- Should include a list with the flatten version (provable by rfl super quick), and a
-- tuple without gIl duplicates that has the same elements. Then g should be constructed by
--sending i to the corresponding gIl
  --{r : ℕ}
  --gIl : Fin r → Ideal S
  --Il : Fin m → List (Ideal S)
  --hIl : ∀ x , x ∈ (List.ofFn (fun i => List.map (Prod.fst) (List.filter (λ p => p.2 < B)
  --  (List.ofFn (fun j => (I i j, N i j)))))).flatten ↔ x ∈ List.ofFn gIl

/-- The interval version of `PrimesBelowBoundCertificate`. Collects the prime ideals above the
  primes in the interval `(A, B]` that have norm less than `C` -/
structure PrimesBelowBoundCertificateInterval (S : Type*) [CommRing S] [Nontrivial S]
    (A B : ℕ) (C : ℕ) where
  /-- The number of prime numbers in `(A, B]`. -/
  m : ℕ
  g : Fin m → ℕ
  /-- The tuple of prime numbers in `(A, B]`-/
  P : Fin m → ℕ
  hP : ∀ p, p ∈ Set.range P ↔ Nat.Prime p ∧ A < p ∧ p ≤ B
  /-- Factorization tuples for the ideals `i`-th prime number in `O`-/
  I : Π i,  Fin (g i) → (Ideal S)
  hC : ∀ i : Fin m, IsPrimesAboveP (P i) (I i)
   /-- Norms corresponding to the factorization of the `i`-th prime in `O`.-/
  N :  Π i,  Fin (g i) → ℕ
  hN : ∀ i, ∀ j, Nat.card (S ⧸ I i j) = N i j
  /-- Lists of ideals over the `i`-th prime, with norm less than `B`-/
  Il : Fin m → List (Ideal S)
  hIl : ∀ i, List.map (Prod.fst) (List.filter (λ p => p.2 < C)
    (List.zip (List.ofFn (I i)) (List.ofFn (N i)))) = Il i

/-- The interval version of `PrimesBelowBoundCertificate`. Collects the prime ideals above the
  primes in the interval `(A, B]` that have norm less than `C` -/
structure PrimesBelowBoundCertificateInterval' (S : Type*) [CommRing S] [Nontrivial S]
    (A B : ℕ) (C : ℕ) where
  /-- The number of prime numbers in `(A, B]`. -/
  m : ℕ
  g : Fin m → ℕ
  /-- The tuple of prime numbers in `(A, B]`-/
  P : Fin m → ℕ
  hP : ∀ p, p ∈ Set.range P ↔ Nat.Prime p ∧ A < p ∧ p ≤ B
  /-- Factorization tuples for the ideals `i`-th prime number in `O`-/
  I : Π i,  Fin (g i) → (Ideal S)
  hC : ∀ i : Fin m, ContainsPrimesAboveP (P i) (I i)
   /-- Norms corresponding to the factorization of the `i`-th prime in `O`.-/
  N :  Π i,  Fin (g i) → ℕ
  hNz : ∀ i j , N i j ≠ 0
  hN : ∀ i, ∀ j, Nat.card (S ⧸ I i j) = N i j
  /-- Lists of ideals over the `i`-th prime, with norm less than `B`-/
  Il : Fin m → List (Ideal S)
  hIl : ∀ i, List.map (Prod.fst) (List.filter (λ p => p.2 < C)
    (List.zip (List.ofFn (I i)) (List.ofFn (N i)))) = Il i

/-- Construct `PrimesBelowBoundCertificate` from interval certificates. -/
def primesBelowBoundCertificate_of_Interval (S : Type*) [CommRing S] [Nontrivial S]
    {r : ℕ} (e : Fin (r + 1) → ℕ) (B : ℕ) (h0 : e 0 = 1) (hr : e (Fin.last r) = B)
    (hl : ∀ (i : Fin r), e i.castSucc  < e (i.castSucc + 1))
    (hC : ∀ (i : Fin r),
      PrimesBelowBoundCertificateInterval S (e i.castSucc) (e (i.castSucc + 1)) (B + 1)) :
      PrimesBelowBoundCertificate S (B + 1) where
 m := ∑ (i : Fin r), (hC i).m
 g := Fin.addCasesIter (fun (i : Fin r) => (hC i).m) (fun i => (hC i).g)
 P := Fin.addCasesIter (fun (i : Fin r) => (hC i).m) (fun i => (hC i).P)
 hP := by
  ext p
  simp only [Set.mem_range, Finset.mem_coe, Nat.mem_primesBelow]
  have auxe : ∀ k, e k < B + 1 := by
    intro k
    refine Fin.reverseInduction ?_ ?_ k
    · simp only [hr, lt_add_iff_pos_right, Nat.lt_one_iff, pos_of_gt]
    · intro i hr
      refine lt_trans (hl i ) ?_
      simp only [Fin.coeSucc_eq_succ, hr]
  constructor
  · rintro ⟨y, hy⟩
    rw [addCasesIter_apply] at hy
    have := (hC ((indexPair (fun i ↦ (hC i).m) y).fst)).hP p
    simp at this
    obtain ⟨hp, hl1,hl2⟩  := this.1 ⟨(indexPair (fun i ↦ (hC i).m) y).2, hy⟩
    refine ⟨lt_of_le_of_lt hl2 (auxe _) , hp⟩
  · rintro ⟨hpB, hp⟩
    have : ∃ (k : Fin r), e k.castSucc < p ∧ p ≤ e (k.castSucc + 1) := by
      by_contra! hc
      have : ∀ k, e k < p := by
        refine Fin.induction ?_ ?_
        · rw [h0]
          exact Nat.Prime.one_lt hp
        · convert hc
          rfl
          simp only [Fin.coeSucc_eq_succ]
      specialize this (Fin.last r)
      rw [hr] at this
      linarith
    obtain ⟨k, hk⟩ := this
    have := ((hC k).hP p ).2 ⟨hp, hk⟩
    simp at this
    obtain ⟨j, hj⟩ := this
    use (indexPairEquiv ((fun (i : Fin r) => (hC i).m))).symm ⟨k, j⟩
    rw [addCasesIter_apply]
    have : (indexPair (fun i ↦ (hC i).m)
      ((indexPairEquiv fun i ↦ (hC i).m).symm ⟨k, j⟩)).fst = k := by
      unfold indexPairEquiv ; simp_rw [Equiv.ofLeftInverseOfCardLE_symm_apply,
        indexPair_right_inverse]
    convert hj
    refine (Fin.heq_ext_iff ?_).mpr ?_
    congr
    unfold indexPairEquiv
    rw [Equiv.ofLeftInverseOfCardLE_symm_apply, indexPair_right_inverse]
 I := by
  intro k
  exact (hC ((indexPair (fun i ↦ (hC i).m) k).1)).I ((indexPair (fun i ↦ (hC i).m) k).2) ∘
    (Fin.cast (addCasesIter_apply _ _ _))
 hC := by
  intro k
  simp_rw [addCasesIter_apply]
  convert (hC (indexPair (fun i ↦ (hC i).m) k).1).hC (indexPair (fun i ↦ (hC i).m) k).2
  rw [addCasesIter_apply]
  (expose_names; exact (Fin.heq_fun_iff e_4).mpr (congrFun rfl))
 N := by
  intro k
  exact (hC ((indexPair (fun i ↦ (hC i).m) k).1)).N ((indexPair (fun i ↦ (hC i).m) k).2) ∘
    (Fin.cast (addCasesIter_apply _ _ _))
 hN := by
  intro k l
  exact (hC (indexPair (fun i ↦ (hC i).m) k).1).hN (indexPair (fun i ↦ (hC i).m) k).2
    ((Fin.cast (addCasesIter_apply _ _ k)) l)
 Il := Fin.addCasesIter (fun (i : Fin r) => (hC i).m) (fun i => (hC i).Il)
 hIl := by
  intro k
  conv => right ; rw [addCasesIter_apply]
  convert (hC (indexPair (fun i ↦ (hC i).m) k).1).hIl (indexPair (fun i ↦ (hC i).m) k).2
  · rw [addCasesIter_apply]
  · (expose_names; exact (Fin.heq_fun_iff e_2).mpr (congrFun rfl))
  · exact addCasesIter_apply (fun i ↦ (hC i).m) (fun i ↦ (hC i).g) k
  · (expose_names; exact (Fin.heq_fun_iff e_2).mpr (congrFun rfl))

/-- Construct `PrimesBelowBoundCertificate` from interval certificates. -/
def primesBelowBoundCertificate_of_Interval' (S : Type*) [CommRing S] [Nontrivial S]
    {r : ℕ} (e : Fin (r + 1) → ℕ) (B : ℕ) (h0 : e 0 = 1) (hr : e (Fin.last r) = B)
    (hl : ∀ (i : Fin r), e i.castSucc  < e (i.castSucc + 1))
    (hC : ∀ (i : Fin r),
      PrimesBelowBoundCertificateInterval' S (e i.castSucc) (e (i.castSucc + 1)) (B + 1)) :
      PrimesBelowBoundCertificate' S (B + 1) where
 m := ∑ (i : Fin r), (hC i).m
 g := Fin.addCasesIter (fun (i : Fin r) => (hC i).m) (fun i => (hC i).g)
 P := Fin.addCasesIter (fun (i : Fin r) => (hC i).m) (fun i => (hC i).P)
 hP := by
  ext p
  simp only [Set.mem_range, Finset.mem_coe, Nat.mem_primesBelow]
  have auxe : ∀ k, e k < B + 1 := by
    intro k
    refine Fin.reverseInduction ?_ ?_ k
    · simp only [hr, lt_add_iff_pos_right, Nat.lt_one_iff, pos_of_gt]
    · intro i hr
      refine lt_trans (hl i ) ?_
      simp only [Fin.coeSucc_eq_succ, hr]
  constructor
  · rintro ⟨y, hy⟩
    rw [addCasesIter_apply] at hy
    have := (hC ((indexPair (fun i ↦ (hC i).m) y).fst)).hP p
    simp at this
    obtain ⟨hp, hl1,hl2⟩  := this.1 ⟨(indexPair (fun i ↦ (hC i).m) y).2, hy⟩
    refine ⟨lt_of_le_of_lt hl2 (auxe _) , hp⟩
  · rintro ⟨hpB, hp⟩
    have : ∃ (k : Fin r), e k.castSucc < p ∧ p ≤ e (k.castSucc + 1) := by
      by_contra! hc
      have : ∀ k, e k < p := by
        refine Fin.induction ?_ ?_
        · rw [h0]
          exact Nat.Prime.one_lt hp
        · convert hc
          rfl
          simp only [Fin.coeSucc_eq_succ]
      specialize this (Fin.last r)
      rw [hr] at this
      linarith
    obtain ⟨k, hk⟩ := this
    have := ((hC k).hP p ).2 ⟨hp, hk⟩
    simp at this
    obtain ⟨j, hj⟩ := this
    use (indexPairEquiv ((fun (i : Fin r) => (hC i).m))).symm ⟨k, j⟩
    rw [addCasesIter_apply]
    have : (indexPair (fun i ↦ (hC i).m)
      ((indexPairEquiv fun i ↦ (hC i).m).symm ⟨k, j⟩)).fst = k := by
      unfold indexPairEquiv ; simp_rw [Equiv.ofLeftInverseOfCardLE_symm_apply,
        indexPair_right_inverse]
    convert hj
    refine (Fin.heq_ext_iff ?_).mpr ?_
    congr
    unfold indexPairEquiv
    rw [Equiv.ofLeftInverseOfCardLE_symm_apply, indexPair_right_inverse]
 I := by
  intro k
  exact (hC ((indexPair (fun i ↦ (hC i).m) k).1)).I ((indexPair (fun i ↦ (hC i).m) k).2) ∘
    (Fin.cast (addCasesIter_apply _ _ _))
 hC := by
  intro k
  simp_rw [addCasesIter_apply]
  convert (hC (indexPair (fun i ↦ (hC i).m) k).1).hC (indexPair (fun i ↦ (hC i).m) k).2
  rw [addCasesIter_apply]
  (expose_names; exact (Fin.heq_fun_iff e_4).mpr (congrFun rfl))
 N := by
  intro k
  exact (hC ((indexPair (fun i ↦ (hC i).m) k).1)).N ((indexPair (fun i ↦ (hC i).m) k).2) ∘
    (Fin.cast (addCasesIter_apply _ _ _))
 hNz := by
  intro k l
  exact (hC (indexPair (fun i ↦ (hC i).m) k).1).hNz (indexPair (fun i ↦ (hC i).m) k).2
    ((Fin.cast (addCasesIter_apply _ _ k)) l)
 hN := by
  intro k l
  exact (hC (indexPair (fun i ↦ (hC i).m) k).1).hN (indexPair (fun i ↦ (hC i).m) k).2
    ((Fin.cast (addCasesIter_apply _ _ k)) l)
 Il := Fin.addCasesIter (fun (i : Fin r) => (hC i).m) (fun i => (hC i).Il)
 hIl := by
  intro k
  conv => right ; rw [addCasesIter_apply]
  convert (hC (indexPair (fun i ↦ (hC i).m) k).1).hIl (indexPair (fun i ↦ (hC i).m) k).2
  · rw [addCasesIter_apply]
  · (expose_names; exact (Fin.heq_fun_iff e_2).mpr (congrFun rfl))
  · exact addCasesIter_apply (fun i ↦ (hC i).m) (fun i ↦ (hC i).g) k
  · (expose_names; exact (Fin.heq_fun_iff e_2).mpr (congrFun rfl))


lemma primesBelowBoundCertificate_of_Interval_Il_apply {S : Type*} [CommRing S] [Nontrivial S]
  {r : ℕ} {e : Fin (r + 1) → ℕ} {B : ℕ} {h0 : e 0 = 1} {hr : e (Fin.last r) = B}
  {hl : ∀ (i : Fin r), e i.castSucc  < e (i.castSucc + 1)}
  {hC : ∀ (i : Fin r),
    PrimesBelowBoundCertificateInterval S (e i.castSucc) (e (i.castSucc + 1)) (B + 1)} (i : Fin r)
  {s : Fin r → ℕ} (hs : ∀ i, s i = (hC i).m) :
  (fun (x : Fin (s i)) => (primesBelowBoundCertificate_of_Interval S e B h0 hr hl hC).Il
    (indexPair_inv (fun j => (hC j).m) ⟨i, finCongr (by simp_rw [hs]) x⟩ ))= ((hC i).Il)
      ∘ (finCongr (by rw [hs])) := by
  refine funext ?_
  intro y
  simp only [primesBelowBoundCertificate_of_Interval ]
  rw [addCasesIter_apply, indexPair_right_inverse]
  rfl

lemma primesBelowBoundCertificate_of_Interval_Il_apply' {S : Type*} [CommRing S] [Nontrivial S]
  {r : ℕ} {e : Fin (r + 1) → ℕ} {B : ℕ} {h0 : e 0 = 1} {hr : e (Fin.last r) = B}
  {hl : ∀ (i : Fin r), e i.castSucc  < e (i.castSucc + 1)}
  {hC : ∀ (i : Fin r),
    PrimesBelowBoundCertificateInterval' S (e i.castSucc) (e (i.castSucc + 1)) (B + 1)} (i : Fin r)
  {s : Fin r → ℕ} (hs : ∀ i, s i = (hC i).m) :
  (fun (x : Fin (s i)) => (primesBelowBoundCertificate_of_Interval' S e B h0 hr hl hC).Il
    (indexPair_inv (fun j => (hC j).m) ⟨i, finCongr (by simp_rw [hs]) x⟩ ))= ((hC i).Il)
      ∘ (finCongr (by rw [hs])) := by
  refine funext ?_
  intro y
  simp only [primesBelowBoundCertificate_of_Interval' ]
  rw [addCasesIter_apply, indexPair_right_inverse]
  rfl

/-- The ideals stored in `PrimesBelowBoundCertificate` are nonzero. -/
lemma zero_ne_mem_of_PrimesBelowCertificate {S : Type*} [CommRing S] [Nontrivial S]
  [CharZero S] (B : ℕ)
  (A : PrimesBelowBoundCertificate S B) : ¬ ⊥ ∈ List.flatten (List.ofFn A.Il) := by
  intro hc
  simp only [List.mem_flatten, List.mem_ofFn, exists_exists_eq_and] at hc
  obtain ⟨a, ha⟩ := hc
  have : A.Il a ⊆ (List.ofFn (A.I a)) := by
    rw [← A.hIl a]
    intro x hx
    simp only [List.mem_map, List.mem_filter, decide_eq_true_eq, Prod.exists, exists_and_right,
      exists_eq_right] at hx
    obtain ⟨y, hy1, hy2⟩ :=  hx
    exact (List.of_mem_zip hy1).1
  have hmem : ⊥ ∈  List.ofFn (A.I a) := this ha
  rw [List.mem_iff_get] at hmem
  simp at hmem
  obtain ⟨i, hi⟩ := hmem
  set ii : Fin (A.g a):= ⟨↑i, id (Eq.mp (congrArg (LT.lt ↑i) List.length_ofFn) i.isLt)⟩
  have := (A.hC a).hPprod
  erw [Finset.prod_eq_zero (Finset.mem_univ ii) hi, Eq.comm, Ideal.span_singleton_eq_bot] at this
  have haP : (A.P a).Prime := by
    have hmemP : A.P a ∈ Nat.primesBelow B := by
      show A.P a ∈ (Nat.primesBelow B : Set ℕ)
      rw [← A.hP]
      simp only [Set.mem_range, exists_apply_eq_apply]
    exact Nat.prime_of_mem_primesBelow hmemP
  simp at this
  rw [this] at haP
  exact Nat.prime_zero_false haP

/-- The ideals stored in `PrimesBelowBoundCertificate'` are nonzero. -/
lemma zero_ne_mem_of_PrimesBelowCertificate' {S : Type*} [CommRing S] [Nontrivial S]
    [CharZero S] (B : ℕ)
    (A : PrimesBelowBoundCertificate' S B) : ¬ ⊥ ∈ List.flatten (List.ofFn A.Il) := by
  intro hc
  simp only [List.mem_flatten, List.mem_ofFn, exists_exists_eq_and] at hc
  obtain ⟨a, ha⟩ := hc
  have : A.Il a ⊆ (List.ofFn (A.I a)) := by
    rw [← A.hIl a]
    intro x hx
    simp only [List.mem_map, List.mem_filter, decide_eq_true_eq, Prod.exists, exists_and_right,
      exists_eq_right] at hx
    obtain ⟨y, hy1, hy2⟩ :=  hx
    exact (List.of_mem_zip hy1).1
  have hmem : ⊥ ∈  List.ofFn (A.I a) := this ha
  rw [List.mem_iff_get] at hmem
  simp at hmem
  obtain ⟨i, hi⟩ := hmem
  set ii : Fin (A.g a):= ⟨↑i, id (Eq.mp (congrArg (LT.lt ↑i) List.length_ofFn) i.isLt)⟩
  have := ((A.hN a) ii).symm ▸  (A.hNz a) ii
  rw [hi] at this
  simp at this


def Ideal.toNonZeroDivisorOfNeZero {R : Type} [CommRing R] [IsDomain R]
  (I : Ideal R) (hp : I ≠ ⊥) : nonZeroDivisors (Ideal R) := by
  refine ⟨I, ?_⟩
  simp only [mem_nonZeroDivisors_iff_ne_zero, Submodule.zero_eq_bot,
    ne_eq, hp, not_false_eq_true]

@[to_additive]
lemma Subgroup.ne_bot_of_index_ne_zero {G : Type*} [Group G]
    [Infinite G] {H : Subgroup G} (h : H.index ≠ 0) : H ≠ ⊥ := by
  intro hc
  rw [hc, Subgroup.index_bot] at h
  exact h (Nat.card_eq_zero_of_infinite)

@[simp]
lemma toAddSubgroup_eq_bot {R M : Type*} [Ring R] [AddCommGroup M] [Module R M]
    {p : Submodule R M} : p.toAddSubgroup = ⊥ ↔ p = ⊥ := by
  exact StrictMono.apply_eq_bot_iff fun a b x ↦ x

lemma Submodule.ne_bot_of_cardQuot_ne_zero
    {R : Type*} {M : Type*} [Ring R] [AddCommGroup M] [Infinite M] [Module R M]
    {S : Submodule R M} (h : S.cardQuot ≠ 0) : S ≠ ⊥ := by
  unfold cardQuot at h
  convert AddSubgroup.ne_bot_of_index_ne_zero h
  exact toAddSubgroup_eq_bot.symm

lemma Ideal.ne_bot_of_norm_pos {R : Type} {n : ℕ} [CommRing R] [IsDomain R]
    [CharZero R] {I : Ideal R} (hp :  Nat.card (R ⧸ I) = n) (hn : n ≠ 0) :
      I ≠ ⊥ := by
  rw [← hp] at hn
  exact Submodule.ne_bot_of_cardQuot_ne_zero hn

def Ideal.toNonZeroDivisorOfNormPos {R : Type} [CommRing R] [IsDomain R] [CharZero R]
  (I : Ideal R) (hp : 0 < Nat.card (R ⧸ I) ) : nonZeroDivisors (Ideal R) := by
  refine Ideal.toNonZeroDivisorOfNeZero I ?_
  intro hc
  rw [hc, Nat.card_congr (RingEquiv.quotientBot R).toEquiv] at hp
  simp only [Nat.card_eq_zero_of_infinite, lt_self_iff_false] at hp


open Classical

/-- If a tuple `g` of ideals contains the flattening of `A.Il` with
`A : PrimesBelowBoundCertificate Oκ B`, then `g` contains every prime ideal of norm less than `B`.-/
lemma le_primes_below_bound_of_PrimesBelowBoundCertificate {B r : ℕ}
    (g : Fin r → Ideal Oκ) (A : PrimesBelowBoundCertificate Oκ B)
    (h : List.flatten (List.ofFn A.Il) ⊆ List.ofFn g) :
    {I : Ideal Oκ | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < B} ⊆ Set.range g := by
  let F : Nat.primesBelow B → Multiset (Ideal Oκ) := by
    rintro ⟨p, hp1⟩
    rw [← Finset.mem_coe, ← A.hP] at hp1
    choose i hi using hp1
    exact ↑(List.ofFn (A.I i))
  have : ∀ i , ∀ I, I ∈ List.ofFn (A.I i) ∧ I.absNorm < B → I ∈ A.Il i := by
    intro i I
    rw [← A.hIl i]
    simp only [List.mem_map, List.mem_filter, decide_eq_true_eq, Prod.exists, exists_and_right,
      exists_eq_right, List.mem_ofFn]
    have heql : ((List.ofFn (A.I i)).zip (List.ofFn (A.N i))).length = (A.g i) := by
        rw [List.length_zip]
        simp only [List.length_ofFn, min_self]
    · rintro ⟨⟨j, hj⟩, hx⟩
      use A.N i j
      rw [List.mem_iff_get]
      constructor
      · use finCongr (heql).symm j
        simp only [finCongr_apply, List.get_eq_getElem, Fin.val_cast, List.getElem_zip,
          List.getElem_ofFn, Fin.eta, hj]
      · rw [← A.hN i j, hj]
        exact hx
  intro x
  rw [Set.mem_range, ← List.mem_ofFn]
  intro hc ; apply h ; revert hc
  rw [List.mem_flatten, primes_below_bound_of_factorization B F]
  simp only [Set.mem_iUnion, Set.mem_setOf_eq, exists_and_right, Subtype.exists, List.mem_ofFn,
    exists_exists_eq_and, and_imp, forall_exists_index]
  intro p hpmem hF hn
  simp only [F, Multiset.mem_coe, List.mem_ofFn] at hF
  obtain ⟨j, hj⟩ := hF
  use @choose (Fin A.m) (fun y ↦ A.P y = p) (cast (congrArg (fun _a ↦ p ∈ _a) (Eq.symm A.hP)) hpmem)
  apply this
  rw [← hj]
  simp only [List.mem_ofFn, exists_apply_eq_apply, true_and]
  rw [hj]
  exact hn
  · intro p I hI
    simp only [F, Multiset.mem_coe, List.mem_ofFn] at hI
    obtain ⟨j, hj⟩ := hI
    rw [← hj]
    exact (A.hC _ ).Ip j
  · intro p
    simp only [F,  Multiset.prod_coe]
    rw [List.prod_ofFn, (A.hC _ ).hPprod]
    congr
    exact @choose_spec (Fin A.m) (fun y ↦ A.P y = ↑p) _

/-- If a tuple `g` of ideals contains the flattening of `A.Il` with
`A : PrimesBelowBoundCertificate Oκ B`, then `g` contains every prime ideal of norm less than `B`.-/
lemma le_primes_below_bound_of_PrimesBelowBoundCertificate_lt {B r : ℕ}
    (g : Fin r → Ideal Oκ) (A : PrimesBelowBoundCertificate' Oκ B)
    (h : List.flatten (List.ofFn A.Il) ⊆ List.ofFn g) :
    {I : Ideal Oκ | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < B} ⊆ Set.range g := by
  let F : Nat.primesBelow B → Multiset (Ideal Oκ) := by
    rintro ⟨p, hp1⟩
    rw [← Finset.mem_coe, ← A.hP] at hp1
    choose i hi using hp1
    exact ↑(List.ofFn (A.I i))
  have : ∀ i , ∀ I, I ∈ List.ofFn (A.I i) ∧ I.absNorm < B → I ∈ A.Il i := by
    intro i I
    rw [← A.hIl i]
    simp only [List.mem_map, List.mem_filter, decide_eq_true_eq, Prod.exists, exists_and_right,
      exists_eq_right, List.mem_ofFn]
    have heql : ((List.ofFn (A.I i)).zip (List.ofFn (A.N i))).length = (A.g i) := by
        rw [List.length_zip]
        simp only [List.length_ofFn, min_self]
    · rintro ⟨⟨j, hj⟩, hx⟩
      use A.N i j
      rw [List.mem_iff_get]
      constructor
      · use finCongr (heql).symm j
        simp only [finCongr_apply, List.get_eq_getElem, Fin.val_cast, List.getElem_zip,
          List.getElem_ofFn, Fin.eta, hj]
      · rw [← A.hN i j, hj]
        exact hx
  intro x
  rw [Set.mem_range, ← List.mem_ofFn]
  intro hc ; apply h ; revert hc
  rw [List.mem_flatten, primes_below_bound_of_factorization' B F]
  simp only [Set.mem_iUnion, Set.mem_setOf_eq, exists_and_right, Subtype.exists, List.mem_ofFn,
    exists_exists_eq_and, and_imp, forall_exists_index]
  intro p hpmem hF hn
  simp only [F, Multiset.mem_coe, List.mem_ofFn] at hF
  obtain ⟨j, hj⟩ := hF
  use @choose (Fin A.m) (fun y ↦ A.P y = p) (cast (congrArg (fun _a ↦ p ∈ _a) (Eq.symm A.hP)) hpmem)
  apply this
  rw [← hj]
  simp only [List.mem_ofFn, exists_apply_eq_apply, true_and]
  rw [hj]
  exact hn
  · intro p I hI
    simp only [F, Multiset.mem_coe, List.mem_ofFn] at hI
    obtain ⟨j, hj⟩ := hI
    rw [← hj]
    exact (A.hC _ ).Ip j
  · intro p q hq
    simp only [F, Multiset.mem_coe, List.mem_ofFn] at hq
    obtain ⟨j, hj⟩ := hq
    rw [← hj]
    --exact (A.hNz _) j
    have := ((A.hN _) j).symm ▸  (A.hNz _) j
    intro hc
    rw [hc] at this
    simp at this
  · intro p
    simp only [F,  Multiset.prod_coe]
    rw [List.prod_ofFn]
    convert (A.hC _ ).hPprod
    grind

-- We don't require definitional equality with the ring of integers.

/-- Version of `le_primes_below_bound_of_PrimesBelowBoundCertificate` using a ring isomorphic
  to `Oκ`. Useful if we have a computational model for it which is not definitionally equal.   -/
lemma le_primes_below_bound_of_PrimesBelowBoundCertificate'{O : Type*} [CommRing O]
    [IsDedekindDomain O] [Module.Free ℤ O]  {B r : ℕ} (φ : O ≃+* Oκ) (g : Fin r → Ideal O)
    (A : PrimesBelowBoundCertificate O B)
    (h : List.flatten (List.ofFn A.Il) ⊆ List.ofFn g) :
    {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < B} ⊆ Set.range g := by
  refine primes_below_bound_of_equiv φ B ?_
  let A' : PrimesBelowBoundCertificate Oκ B :=
  { m := A.m
    g := A.g
    P := A.P
    hP := A.hP
    I := fun i => (Ideal.map φ) ∘ (A.I i)
    hC := fun i =>
      { Ip :=  by
          intro j
          have := (A.hC i).Ip j
          exact Ideal.map_isPrime_of_equiv φ (I := (A.I i) j)
        hPprod := by
          have := (A.hC i ).hPprod
          apply_fun (Ideal.mapHom φ) at this
          rw [map_prod, Ideal.mapHom_apply, Ideal.map_span] at this
          simp only [Ideal.mapHom_apply, Set.image_singleton, map_natCast] at this
          exact this }
    N := A.N
    hN := by
      intro i j
      rw [← A.hN i j]
      refine Nat.card_congr ?_
      exact (Ideal.quotientEquiv _ ((A.I i j).map φ) φ rfl).toEquiv.symm
    Il := fun i => List.map (Ideal.map φ) (A.Il i)
    hIl := by
      intro i
      rw [← A.hIl i, ← List.map_ofFn, List.zip_map_left,
        List.filter_map, ← List.comp_map, ← List.comp_map]
      rfl }
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate _ A' ?_
  unfold A'
  dsimp
  erw [← List.map_ofFn, ← List.map_ofFn (f := g), ← List.map_flatten]
  refine List.map_subset _ ?_
  exact h

/-- Version of `le_primes_below_bound_of_PrimesBelowBoundCertificate` using a ring isomorphic
  to `Oκ`. Useful if we have a computational model for it which is not definitionally equal.   -/
lemma le_primes_below_bound_of_PrimesBelowBoundCertificate_le' {O : Type*} [CommRing O]
    [IsDedekindDomain O] [Module.Free ℤ O]  {B r : ℕ} (φ : O ≃+* Oκ) (g : Fin r → Ideal O)
    (A : PrimesBelowBoundCertificate' O B)
    (h : List.flatten (List.ofFn A.Il) ⊆ List.ofFn g) :
    {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < B} ⊆ Set.range g := by
  refine primes_below_bound_of_equiv φ B ?_
  let A' : PrimesBelowBoundCertificate' Oκ B :=
  { m := A.m
    g := A.g
    P := A.P
    hP := A.hP
    I := fun i => (Ideal.map φ) ∘ (A.I i)
    hC := fun i =>
      { Ip :=  by
          intro j
          have := (A.hC i).Ip j
          exact Ideal.map_isPrime_of_equiv φ (I := (A.I i) j)
        hPprod := by
          have := Ideal.map_mono (f := φ) (A.hC i ).hPprod
          rw [← Ideal.mapHom_apply, ← Ideal.mapHom_apply,
            map_prod, Ideal.mapHom_apply, Ideal.map_span] at this
          simp only [Ideal.mapHom_apply, Set.image_singleton, map_natCast] at this
          exact this}
    N := A.N
    hN := by
      intro i j
      rw [← A.hN i j]
      refine Nat.card_congr ?_
      exact (Ideal.quotientEquiv _ ((A.I i j).map φ) φ rfl).toEquiv.symm
    hNz := A.hNz
    Il := fun i => List.map (Ideal.map φ) (A.Il i)
    hIl := by
      intro i
      rw [← A.hIl i, ← List.map_ofFn, List.zip_map_left,
        List.filter_map, ← List.comp_map, ← List.comp_map]
      rfl }
  refine le_primes_below_bound_of_PrimesBelowBoundCertificate_lt _ A' ?_
  unfold A'
  dsimp
  erw [← List.map_ofFn, ← List.map_ofFn (f := g), ← List.map_flatten]
  refine List.map_subset _ ?_
  exact h

end CertificateBound
