import IdealArithmetic.Examples.NF3_1_24843_1.ClassGroupSaturated3_1_24843_1_3
import IdealArithmetic.Examples.NF3_1_24843_1.RelationIdeals3_1_24843_1F0
import IdealArithmetic.Examples.NF3_1_24843_1.RelationIdeals3_1_24843_1F1
import IdealArithmetic.Examples.NF3_1_24843_1.PrimesBelowCert3_1_24843_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with with α root of polynomial `X^3 - 91`.
Class group structure `[3, 3]`, generated by class of ideals `[(2, a + 1), (3, 1/3*a^2 + 1/3*a + 1/3)]`. -/

/- Ring of integers with basis `[1, a, 1/3*a^2 + 1/3*a + 1/3]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible 

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

-- These instances were not needed previously. Additional in this new Lean/Mathlib version 
instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 3 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out 

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [3]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateLists K 3 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M3
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [3] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl



instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B 

-- Additional in this new Lean/Mathlib version 
instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O


def SturmRC : SturmBuilderOfList [[-91, 0, 0, 1], [0, 0, 3], [819]] [-91, 0, 0, 1] [0, 0, 3] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic 
    have hi : i < 2 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [9]
  f := [1]
  epos := by decide
  fpos := by decide
  Q := [[0, 3]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 1 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^3 - 91
  l := [-91, 0, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-91, 0, 0, 1], [0, 0, 3], [819]]
  SB := SturmRC
  k := 1
  r := 2
  hr := by decide
  hreq := by decide 

lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
 suffices ¬ 3 ∣ 2 from ?_
 · convert this 
   rw [O_integral_closure, ← Fintype.card_eq_nat_card,
   ←  NumberField.Units.torsionOrder_eq_two_of_odd_finrank (by erw [K_finrank] ; decide)]
   rfl
 · decide

def NPCU3 : pMaximalUnitsCertificateNDvdT O 3 where 
 hp := by decide
 r := 1
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
 t := 3
 hrle := by decide
 q := ![7, 13, 31]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat3.hq7
  | 1 => exact Sat3.hq13
  | 2 => exact Sat3.hq31
 I := ![Sat3.I0, Sat3.I1, Sat3.I2]
 hcard := fun i =>
  match i with  
  | 0 => Sat3.N0
  | 1 => Sat3.N1
  | 2 => Sat3.N2
 ζ := ![3, 2, 3]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat3.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat3.R13) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat3.R31) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion3
 M := ![![2], ![2], ![1]]
 hM1 := by 
  intro i j
  fin_cases i <;> fin_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat3.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log20] ; decide
 Minv := ![![2]]
 hInv := by decide

def NPSU3 : pSaturatedClassGroupCertificateNDvdT 3 ![J0, J1] ![3, 3] where 
 topMaximalUnitsCertificateNDvdT := NPCU3
 a := ![alpha0,alpha1]
 γ := 2
 hc := by decide
 ψ := ![0, 1]
 iψ := ![0, 1] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide
  | 1 => by convert J1_pow3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide
 N := ![![1, 1], ![1, 0], ![0, 2]]
 hM2 := by 
  intro (i : Fin 3) j
  match i , j with 
  | 0, 0 => exact Sat3.Log01
  | 0, 1 => exact Sat3.Log02
  | 1, 0 => exact Sat3.Log11
  | 1, 1 => exact Sat3.Log12
  | 2, 0 => exact Sat3.Log21
  | 2, 1 => exact Sat3.Log22
 hDl := by decide 
 NInv := ![![1, 2, 1], ![1, 0, 1], ![1, 2, 0]]
 hN := by decide 

lemma T_discr : T.discr = -223587 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]
  decide

theorem K_discr : NumberField.discr K = -24843 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 1 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : MinkowskiBound K ≤ (44.60638176300717 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √24843 ≤ 157.616633 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 2/9 * √24843 ≤ 35.035918 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}


def e := ![15, 1]
def s := ![11, 3]
def g : (i : Fin 2) → Fin (e i) → Ideal O := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![I2N0, I2N1, I3N0, I3N1, I5N0, I5N1, I7N0, I11N1, I13N0, I17N1, I23N1, I29N1, I31N0, I31N1, I31N2]
  exact ![I41N1]

def BM : (i : Fin 2) → Fin (e i) → (Fin 2 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![2, 0], ![1, 0], ![0, 1], ![0, 1], ![1, 2], ![2, 1], ![1, 1], ![0, 1], ![2, 2], ![2, 0], ![1, 0], ![2, 2], ![1, 2], ![1, 2], ![1, 2]]
  exact ![![2, 2]]

lemma primesGenerationAux0  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 0)) => PB45.Il ((indexPair_inv s) ⟨0,x⟩))).flatten ↔ y ∈ List.ofFn (g 0) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I2N0, I2N1, I3N0, I3N0, I3N1, I5N0, I5N1, I7N0, I7N0, I7N0, I11N1, I13N0, I13N0, I13N0, I17N1, I23N1, I29N1, I31N0, I31N1, I31N2] ↔ y ∈ [I2N0, I2N1, I3N0, I3N1, I5N0, I5N1, I7N0, I11N1, I13N0, I17N1, I23N1, I29N1, I31N0, I31N1, I31N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

  
lemma primesGenerationAux1  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 1)) => PB45.Il ((indexPair_inv s) ⟨1,x⟩))).flatten ↔ y ∈ List.ofFn (g 1) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I41N1] ↔ y ∈ [I41N1]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

  
lemma primesGenerationAux {x} : x ∈ (List.ofFn PB45.Il).flatten ↔ x ∈ List.ofFn (Fin.addCasesIter e g) := by
  refine (list_flatten_eq_list_addCasesIter g (s := s) PB45.Il ?_ x)
  rintro ⟨i, hi⟩ x
  interval_cases i 
  · exact primesGenerationAux0
  · exact primesGenerationAux1

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 45} ⊆ Set.range (Fin.addCasesIter e g) := 
  le_primes_below_bound_of_PrimesBelowBoundCertificate_le' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv ((Fin.addCasesIter e g)) PB45 (fun _ hx => primesGenerationAux.1 hx)

def g' : Fin 16 → nonZeroDivisors (Ideal O) := by
  intro i
  have : (Fin.addCasesIter e g) i ∈ (List.ofFn PB45.Il).flatten := by 
    simp only [primesGenerationAux, List.mem_ofFn, exists_apply_eq_apply]
  exact Ideal.toNonZeroDivisorOfNeZero ((Fin.addCasesIter e g) i) 
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate' _ PB45) (hc ▸ this) ))

def x : Fin 2 → Ideal O := ![J0,J1] 

def x' :  Fin 2 → nonZeroDivisors (Ideal O) := by 
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (x i) (?_ )
  -- v4.32: the old `rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff …]` no longer
  -- fires (two distinct `Zero (Ideal O)` instances: `⊥` vs the `MonoidWithZero` 0).
  -- Argue by contradiction: if `xᵢ = ⊥` then `xᵢ ^ nᵢ ≤ ⊥`, but the certificate says
  -- `xᵢ ^ nᵢ` is a nonzero principal ideal.
  intro hc
  have hle : x i ^ ![3, 3] i = ⊥ :=
    le_bot_iff.mp ((Ideal.pow_le_self (by fin_cases i <;> decide)).trans hc.le)
  rw [show x i ^ ![3, 3] i = _ from NPSU3.h i] at hle
  revert hle
  simp only [imp_false, ne_eq, Ideal.span_singleton_eq_bot, NPSU3]
  fin_cases i    
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 
  · dsimp [alpha1] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma g'_apply : ∀ (i : Fin 16), ↑(g' i) = (Fin.addCasesIter e g) i := by
  intro i
  rfl

lemma x'_apply : ∀ (i : Fin 2), ↑(x' i) = x i := by
  intro i
  rfl 
  
lemma relations_proof0 (i : Fin 15) : IsInClass O x (g 0 i) (BM 0 i) := by
  show IsInClass O x (g 0 i) (![![2, 0], ![1, 0], ![0, 1], ![0, 1], ![1, 2], ![2, 1], ![1, 1], ![0, 1], ![2, 2], ![2, 0], ![1, 0], ![2, 2], ![1, 2], ![1, 2], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R7N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R13N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R17N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R23N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R29N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R31N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R31N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R31N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof1 (i : Fin 1) : IsInClass O x (g 1 i) (BM 1 i) := by
  show IsInClass O x (g 1 i) (![![2, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R41N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      g'_apply x'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop g BM (IsInClass O x) ?_
    rintro ⟨i, hi⟩
    interval_cases i 
    · exact relations_proof0
    · exact relations_proof1

def ClassGroupO_equiv : (∀ i : Fin 2 , (ZMod (![3, 3] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 2), NeZero (![3, 3] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate x'_apply NPSU3.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![3, 3] i = ∏ i, (![3] i) ^ (![2] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [3] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![3]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩ 
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases 
  by_cases h : p = 3
  simp_rw [h] ; right
  exact NPSU3 
  omega 
 
def class_group_equiv : (∀ i : Fin 2 , (ZMod (![3, 3] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_9 : NumberField.classNumber K = 9 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide 
