import Mathlib.RingTheory.IsAdjoinRoot
import Mathlib.LinearAlgebra.Dimension.DivisionRing
import Mathlib.LinearAlgebra.FreeModule.PID
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.RingTheory.Adjoin.PowerBasis
import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
import Mathlib.Algebra.Module.Submodule.RestrictScalars
import Mathlib.Tactic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Algebra.Group.Subgroup.Finsupp
import Mathlib.NumberTheory.NumberField.Units.Basic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.GroupTheory.Complement
import Mathlib.LinearAlgebra.Dimension.OrzechProperty

import IdealArithmetic.DedekindProject.TimesTable.TimesTableAsLists
import IdealArithmetic.DedekindProject.TimesTable.Defs
import IdealArithmetic.DedekindProject.Auxiliary

/- # Ideal arithmetic

We define certificates for basic ideal operations.

## Main definition
- `IdealEqSpanCertificate'`: to certify an `R`-spanning set of an ideal.
- `IdealEqCertificateO'` : certifies equality of ideals given `O`-generators.
- `BasisOfEqSpan`: an `R`-basis of an ideal given the right number of `R`-generators.
- `IdealMemCertificate` : certifies membership in an ideal.
- `IdealMulEqCertificate'`: certifies a multiplication of ideals.
- `IsInClass` : expresses that two ideals belong to the same ideal class.


-/

section I

variable {S : Type*} {O R : Type*} [CommRing O] [CommRing R] [CommRing S]
open BigOperators Classical Module

/-- Condition for containment if the `R`-span is also an `S`-module. -/
lemma submodule_span_le_span_iff [Module R O] [Module S O] {ι τ : Type _} [Fintype ι] [Fintype τ]
  (v : ι → O) (w : τ → O) (I : Set O) (hI : I = Submodule.span R (Set.range w))
  (hsmul : ∀ (s : S) {x : O}, x ∈ I → s • x ∈ I) :
  (Submodule.span S (Set.range v)).carrier ⊆ (Submodule.span R (Set.range w)) ↔
  ∀ (i : ι), (∃ (a : τ → R), v i = ∑ (j : τ), (a j) • (w j) ) := by
  constructor
  · intro h i
    have hvin : v i ∈ (Submodule.span S (Set.range v)).carrier := by
      exact Submodule.subset_span (R := S) (by simp only [Set.mem_range, exists_apply_eq_apply] )
    have hvw := h hvin
    erw [Submodule.mem_span_range_iff_exists_fun] at hvw
    obtain ⟨a, ha⟩ :=  hvw
    use a
    exact ha.symm
  · intro h
    have : ∀ i , v i ∈ (Submodule.span R (Set.range w)) := by
      intro i
      rw [Submodule.mem_span_range_iff_exists_fun]
      obtain ⟨a, ha⟩ := h i
      use a
      exact ha.symm
    let P : Submodule S O :=
      { carrier := I
        add_mem' := by
          rw [hI]
          intro a b ha hb
          exact (Submodule.add_mem_iff_right (Submodule.span R (Set.range w)) ha).mpr hb
        zero_mem' := by
          rw [hI]
          exact zero_mem (Submodule.span R (Set.range w))
        smul_mem' := by
          exact hsmul }
    have hleaux : Set.range v ⊆ P := by
      rintro a ⟨i, hi⟩
      simp only [Submodule.coe_set_mk, AddSubmonoid.coe_set_mk, AddSubsemigroup.coe_set_mk, P]
      rw [← hi, hI, SetLike.mem_coe]
      exact this i
    rw [← Submodule.span_le] at hleaux
    rw [← hI]
    exact hleaux

/-- If `B` spans `O` as `ℤ`-module, then the ideal generated by `v` is the `R`-span of `vᵢ * vⱼ`. -/
lemma ideal_eq_R_span [Algebra R O] {ι τ : Type _} [Fintype ι] [Fintype τ]
    (v : ι → O) (B : τ → O) (hspan : ⊤ = Submodule.span R (Set.range B)) :
    (Ideal.span (Set.range v)).carrier =
    Submodule.span R (Set.range (fun ⟨i, j⟩ => (v i) * (B j) : ι × τ → O )) := by
  ext x
  constructor
  · intro hx
    erw [Submodule.mem_span_range_iff_exists_fun] at hx
    obtain ⟨c, hc⟩ := hx
    have hmem : ∀ i , c i ∈ Submodule.span R (Set.range B) := by
      intro i
      rw [← hspan]
      simp only [Submodule.mem_top]
    simp_rw [Submodule.mem_span_range_iff_exists_fun] at hmem
    let f : ι → (τ → R) := fun i => ((hmem i).choose)
    have hceq : ∀ i , ∑ j : τ , (f i j) • (B j) = c i := by
      intro i
      exact (hmem i).choose_spec
    simp_rw [← hceq] at hc
    erw [Submodule.mem_span_range_iff_exists_fun, ← hc]
    use (fun ⟨i, j⟩ => f i j)
    dsimp
    let F : ι → (τ → O) := fun i => (fun j => (f i j) • ((v i) * (B j)))
    rw [Fintype.sum_prod_type' F]
    simp_rw [Finset.sum_mul]
    congr ; ext i ; congr ; ext j
    rw [Algebra.smul_mul_assoc, mul_comm]
  · intro hx
    erw [Submodule.mem_span_range_iff_exists_fun] at hx
    obtain ⟨c, hc⟩ := hx
    rw [← hc]
    refine Submodule.sum_mem _ ?_
    intro i _
    dsimp
    rw [mul_comm, ← Algebra.smul_mul_assoc]
    refine Ideal.mul_mem_left _ _ (Ideal.subset_span ?_)
    exact Set.mem_range_self i.1


lemma ideal_eq_R_span' [Algebra R O] {ι τ κ: Type _} [Fintype ι] [Fintype τ]
  [Fintype κ] (v : ι → O) (B : τ → O) (w : κ → O)
  (hspan : ⊤ = Submodule.span R (Set.range B))
  (h1 : ∀ k, (∃ (f : ι → τ → R) , w k = ∑ i , ∑ j , f i j • ((v i) * (B j))))
  (h2 : ∀ i j , (∃ (g : κ → R), (v i) * (B j) = ∑ k, (g k) • (w k) )) :
   (Ideal.span (Set.range v)).carrier = Submodule.span R (Set.range w) := by
  rw [ideal_eq_R_span v B hspan]
  refine subset_antisymm ?_ ?_
  erw [submodule_span_le_span_iff _ _ ((Submodule.span R (Set.range w)).carrier)]
  · rintro ⟨i , j⟩
    use (h2 i j).choose
    exact (h2 i j).choose_spec
  · rfl
  · intro s x hx
    exact (Submodule.span R (Set.range w)).smul_mem' s hx
  erw [submodule_span_le_span_iff]
  · intro k
    use (fun ⟨i , j⟩ =>  (h1 k).choose i j)
    simp_rw [(h1 k).choose_spec]
    exact Eq.symm (Fintype.sum_prod_type fun x ↦ (h1 k).choose x.1 x.2 • (v x.1 * B x.2))
  · exact (Submodule.span R (Set.range (fun ⟨i, j⟩ => (v i) * (B j) : ι × τ → O ))).carrier
  · rfl
  · intro s x hx
    exact Submodule.smul_mem' _ s hx

-- v are O-generators and w are Z-generators. we include them as parameters so we can easily reuse
-- them and we don't have to use projections in the correctness statement. Since corrdinates are
-- in respect to a basis, we include the times table as a parameter as well.

/- For an ideal `I`, given `O`-generators `v` and `R`-generators `w`, this certifies that
  `I` equals the `R`-span of `w`. -/
structure IdealEqSpanCertificate [Algebra R O] {r n m : ℕ}
   (TT  : TimesTable (Fin r) R O) (I : Ideal O)
   (v : Fin m → Fin r → R) (w : Fin n → Fin r → R)  where
  /-- Times table in term of lists. -/
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hieq : I = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (v i)))
  f : Fin n → Fin m → Fin r → R
  g : Fin m → Fin r → Fin n → R
  M : Fin m → Fin r → Fin r → R -- products (v i) * (B j)
  hmulB : ∀ i j, table_mul_list T (List.ofFn (v i)) (List.ofFn (fun k => if k = j then 1 else 0 ))
    = List.ofFn (M i j)
  hle1 : ∀ k , List.ofFn (w k) = List.sum (List.ofFn (fun i => List.sum
    (List.ofFn (fun j => List.mulPointwise (f k i j) (List.ofFn (M i j) ) ))))
  hle2 : ∀ i j, List.ofFn (M i j) =
    List.sum (List.ofFn (fun k => List.mulPointwise (g i j k) (List.ofFn (w k))))

/-- Proof of correctness of `IdealEqSpanCertificate`. -/
lemma ideal_eq_of_IdealEqSpanCertificate [Algebra R O] {r n m : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {I : Ideal O}
    {v : Fin m → Fin r → R} {w : Fin n → Fin r → R} (A : IdealEqSpanCertificate TT I v w) :
    I.carrier = Submodule.span R (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  rw [A.hieq]
  have aux := A.hmulB
  simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq] at aux
  have hmulaux :=
    fun i j => table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (aux i j).symm
  have : ∀ j , TT.basis.equivFun.symm (fun k ↦ if k = j then 1 else 0) = TT.basis j := by
    simp only [Basis.equivFun_symm_apply, ite_smul, one_smul, zero_smul, Finset.sum_ite_eq',
      Finset.mem_univ, ↓reduceIte, implies_true]
  simp_rw [this] at hmulaux
  refine ideal_eq_R_span' _ (TT.basis) _ ?_ ?_ ?_
  · exact Eq.symm (Basis.span_eq TT.basis)
  · intro k
    use (A.f k)
    have hle1 := A.hle1
    simp_rw [List.mulPointwise_ofFn, ← List.sum_ofFn' (Ne.symm (NeZero.ne' r))] at hle1
    convert table_sum_smul' TT.basis _ _ (hle1 k)
    simp_rw [hmulaux]
    simp only [Basis.equivFun_symm_apply, map_sum, map_smul]
  · intro i j
    use (A.g i j)
    simp_rw [hmulaux]
    refine table_sum_smul TT.basis _ _ _ ?_
    exact A.hle2 i j


/-- Purely computational version of `IdealEqSpanCertificate`, with  times table in term of lists. -/
structure IdealEqSpanCertificate' {r n m : ℕ}
  (T : Fin r → Fin r → List R) (v : Fin m → Fin r → R)
  (w : Fin n → Fin r → R)  where
  f : Fin n → Fin m → Fin r → R
  g : Fin m → Fin r → Fin n → R
  M : Fin m → Fin r → Fin r → R -- products (v i) * (B j)
  hmulB : ∀ i j, table_mul_list T (List.ofFn (v i)) (List.ofFn (fun k => if k = j then 1 else 0 ))
    = List.ofFn (M i j)
  hle1 : ∀ k , List.ofFn (w k) = List.sum (List.ofFn (fun i => List.sum
    (List.ofFn (fun j => List.mulPointwise (f k i j) (List.ofFn (M i j) ) ))))
  hle2 : ∀ i j, List.ofFn (M i j) =
    List.sum (List.ofFn (fun k => List.mulPointwise (g i j k) (List.ofFn (w k))))

/-- Proof of correctness of `IdealEqSpanCertificate'`. -/
lemma ideal_eq_of_IdealEqSpanCertificate' [Algebra R O] {r n m : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {I : Ideal O}
    {v : Fin m → Fin r → R} {w : Fin n → Fin r → R}
    (hieq : I = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (v i))))
    (A : IdealEqSpanCertificate' T v w) :
    I.carrier = Submodule.span R (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  refine ideal_eq_of_IdealEqSpanCertificate (TT := TT) (I := I) (v := v) (w := w) ?_
  exact
  { T := T ,heq := heq, hieq := hieq, f := A.f, g := A.g, M := A.M
    hmulB := A.hmulB, hle1 := A.hle1, hle2 := A.hle2 }

/-- Certificate for `I ≤ J` given `R`-generators. -/
structure IdealLeCertificate [Algebra R O] {r n m : ℕ}
    (B  : Basis (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R)  where
  hieq1 : I.carrier = Submodule.span R (Set.range (fun i => B.equivFun.symm (v i)))
  hieq2 : J.carrier = Submodule.span R (Set.range (fun j => B.equivFun.symm (w j)))
  g : Fin m → Fin n → R
  hle2 : ∀ i, List.ofFn (v i) =
    List.sum (List.ofFn (fun k => List.mulPointwise (g i k) (List.ofFn (w k))))

/-- Proof of correctness for `IdealLeCertificate`. -/
lemma ideal_le_of_certificate [Algebra R O] {r n m : ℕ}
   (B  : Basis (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
   (w : Fin n → Fin r → R) (A : IdealLeCertificate B I J v w) : I ≤ J := by
  show (I.carrier ⊆ J.carrier)
  rw [A.hieq1, A.hieq2]
  convert (submodule_span_le_span_iff (fun i => B.equivFun.symm (v i))
    (fun i => B.equivFun.symm (w i))
    _ rfl (by intro s hs ; exact fun a ↦ SMulMemClass.smul_mem s a)).2 ?_
  · rfl
  · intro i
    use (A.g i)
    refine table_sum_smul B w (v i) (A.g i) ?_
    exact (A.hle2 i)

/-- Certificate for `I ≤ J` using `O`-generators for `J` and `S`-generators for `I`. -/
structure IdealLeCertificateO [Algebra R O] (S : Type*) [CommRing S] [Algebra S O]
    {r n m : ℕ} (TT  : TimesTable (Fin r) R O)  (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) where
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hieq1 : I.carrier = Submodule.span S (Set.range (fun i => TT.basis.equivFun.symm (v i)))
  hieq2 : J = Ideal.span (Set.range (fun j => TT.basis.equivFun.symm (w j)))
  g : Fin m → Fin n → Fin r → R
  hle2 : ∀ i, List.ofFn (v i) =
    List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (g i k)) (List.ofFn (w k))))

/-- Proof of correctness of `IdealLeCertificateO`. -/
lemma ideal_le_of_IdealLeCertificateO [Algebra R O] (S : Type*) [CommRing S] [Algebra S O]
    {r n m : ℕ} (TT  : TimesTable (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) (A : IdealLeCertificateO S TT I J v w) : I ≤ J := by
  show I.carrier ⊆ J.carrier
  rw [A.hieq1, A.hieq2]
  unfold Ideal.span
  erw [submodule_span_le_span_iff (S := S) (fun j => TT.basis.equivFun.symm (v j))
    (fun j => TT.basis.equivFun.symm (w j)) J.carrier ?_ ?_]
  · intro i
    use (fun j => TT.basis.equivFun.symm (A.g i j) )
    simp_rw [smul_eq_mul]
    refine table_sum_mul TT.table TT.basis TT.basis_mul_basis _ _ _ ?_
    simp_rw [← table_mul_eq_table_mul' TT.table A.T A.heq]
    exact A.hle2 i
  · rw [A.hieq2]
    rfl
  · intro s x hx
    rw [algebra_compatible_smul O s x]
    exact J.smul_mem' ((algebraMap S O) s) hx

/-- Certifies equality of ideals from `O`-generators. -/
structure IdealEqCertificateO [Algebra R O]
    {r n m : ℕ} (TT  : TimesTable (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) where
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hieq1 : I = Ideal.span (Set.range (fun i => TT.basis.equivFun.symm (v i)))
  hieq2 : J = Ideal.span (Set.range (fun j => TT.basis.equivFun.symm (w j)))
  g : Fin m → Fin n → Fin r → R
  h : Fin n → Fin m → Fin r → R
  hle1 : ∀ i, List.ofFn (v i) =
    List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (g i k)) (List.ofFn (w k))))
  hle2 : ∀ i, List.ofFn (w i) =
    List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (h i k)) (List.ofFn (v k))))

/-- Proof of correctness of `IdealEqCertificateO`. -/
lemma ideal_eq_of_IdealEqCertificateO [Algebra R O]
    {r n m : ℕ} (TT  : TimesTable (Fin r) R O) (I : Ideal O) (J : Ideal O) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) (A : IdealEqCertificateO TT I J v w) : I = J := by
  let A1 : IdealLeCertificateO O TT I J v w :=
    { T := A.T
      heq := A.heq
      hieq1 := by
        rw [A.hieq1] ; rfl
      hieq2 := A.hieq2
      g := A.g
      hle2 := A.hle1 }
  let A2 : IdealLeCertificateO O TT J I w v :=
    { T := A.T
      heq := A.heq
      hieq1 := by
        rw [A.hieq2] ; rfl
      hieq2 := A.hieq1
      g := A.h
      hle2 := A.hle2 }
  refine le_antisymm ?_ ?_
  · exact ideal_le_of_IdealLeCertificateO _ TT I J v w A1
  · exact ideal_le_of_IdealLeCertificateO _ TT J I w v A2

/-- Purely computational version of `IdealEqCertificateO`, with  times table in term of lists. -/
structure IdealEqCertificateO'
    {r n m : ℕ} (T : Fin r → Fin r → List R)  (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) where
    g : Fin m → Fin n → Fin r → R
    h : Fin n → Fin m → Fin r → R
    hle1 : ∀ i, List.ofFn (v i) =
      List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (g i k)) (List.ofFn (w k))))
    hle2 : ∀ i, List.ofFn (w i) =
      List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (h i k)) (List.ofFn (v k))))

/-- Proof of correctness of `IdealEqCertificateO'`. -/
lemma ideal_eq_of_IdealEqCertificateO' [Algebra R O]
  {r n m : ℕ} {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
  (heq : ∀ i j , T i j = List.ofFn (TT.table i j))
  {I : Ideal O} {J : Ideal O} {v : Fin m → Fin r → R} {w : Fin n → Fin r → R}
  (hieq1 : I = Ideal.span (Set.range (fun i => TT.basis.equivFun.symm (v i))))
  (hieq2 : J = Ideal.span (Set.range (fun j => TT.basis.equivFun.symm (w j))))
   (A : IdealEqCertificateO' T v w) : I = J := by
  refine ideal_eq_of_IdealEqCertificateO TT I J v w ?_
  exact { T := T, heq := heq, hieq1 := hieq1, hieq2 := hieq2
          g := A.g, h := A.h, hle1 :=  A.hle1, hle2 := A.hle2 }

/- Relation describing when two representations define the same ideal.  -/
def IdealEq {r m n} (T : Fin r → Fin r → List R) (v : Fin m → Fin r → R)
    (w : Fin n → Fin r → R) : Prop := Nonempty (IdealEqCertificateO' T v w)

lemma ideal_eq_of_IdealEq [Algebra R O]
  {r n m : ℕ} {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
  (heq : ∀ i j , T i j = List.ofFn (TT.table i j))
  {I J : Ideal O}{v : Fin m → Fin r → R} {w : Fin n → Fin r → R}
  (hieq1 : I = Ideal.span (Set.range (fun i => TT.basis.equivFun.symm (v i))))
  (hieq2 : J = Ideal.span (Set.range (fun j => TT.basis.equivFun.symm (w j)))) :
    IdealEq T v w → I = J := fun ⟨A⟩ => ideal_eq_of_IdealEqCertificateO' heq hieq1 hieq2 A

/-- Certificate for membership `a ∈ I` from `R`-generators. -/
structure IdealMemCertificate [Algebra R O] {r m : ℕ} (B  : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin m → Fin r → R)  (a : Fin r → R) where
  hieq : I.carrier = Submodule.span R (Set.range (fun i => B.equivFun.symm (v i)))
  g : Fin m → R
  hmem : List.ofFn a = List.sum (List.ofFn (fun k => List.mulPointwise (g k) (List.ofFn (v k))))

/-- Proofs correctness of `IdealMemCertificate`. -/
lemma mem_of_certificate [Algebra R O] {r m : ℕ} (B  : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin m → Fin r → R)  (a : Fin r → R) (A : IdealMemCertificate B I v a) :
    B.equivFun.symm a ∈ I := by
  show B.equivFun.symm a ∈ I.carrier
  erw [A.hieq, Submodule.mem_span_range_iff_exists_fun]
  use A.g
  symm
  refine table_sum_smul B v a (A.g) (A.hmem)

lemma linear_independent_of_top_le_span_of_card_eq_rank
  {τ : Type*} {M : Type*} [Fintype τ] [IsDomain R]
  [AddCommGroup M] [Module R M] (B : Basis τ R M) {b : τ → M}
  (hmem : ⊤ ≤ Submodule.span R (Set.range b)) : LinearIndependent R b := by
  refine linearIndependent_of_top_le_span_of_card_le_finrank hmem ?_
  rw [Module.finrank_eq_card_basis B]

/-- If `I` is `R`-generated by the collection `v` with the same number of elements
  as the rank of `O`, then this is a basis for `I`. -/
noncomputable def BasisOfEqSpan {τ : Type*} [Fintype τ] [IsDomain R] [IsPrincipalIdealRing R]
    [IsDomain O] [Algebra R O] (B : Basis τ R O) (I : Ideal O) (hI : I ≠ ⊥) (v : τ → O)
    (heq : I.carrier = Submodule.span R (Set.range v)) : Basis τ R I := by
  have hmem : ∀ i , v i ∈ I := by
    intro i
    show (v i) ∈ I.carrier
    rw [heq]
    refine Submodule.subset_span ⟨i, rfl⟩
  let v' := fun i => (⟨v i, hmem i⟩ : I)
  let f : I →ₗ[R] O :=
    { toFun := Subtype.val
      map_add' := fun x y ↦ rfl
      map_smul' := fun m x ↦ rfl }
  have hle : ⊤ ≤ Submodule.span R (Set.range v') := by
    have hf : Function.Injective f := by simp only [LinearMap.coe_mk, AddHom.coe_mk,
    Subtype.val_injective, f]
    have hvv : v = f ∘ v' := rfl
    intro x ?_
    rw [← Submodule.apply_mem_span_image_iff_mem_span hf, ← Set.range_comp, ← hvv]
    show (f x ∈ ((Submodule.span R (Set.range v) : Set O) ))
    rw [← heq]
    exact x.2
  refine Basis.mk (R := R) (v := v') ?_ ?_
  refine linearIndependent_of_top_le_span_of_card_eq_finrank hle ?_
  rw [Module.finrank_eq_card_basis (Ideal.selfBasis B I hI) ]
  exact hle

lemma BasisOfEqSpan_apply  {τ : Type*} [Fintype τ] [IsDomain R] [IsPrincipalIdealRing R]
    [IsDomain O] [Algebra R O] (B : Basis τ R O) (I : Ideal O) (hI : I ≠ ⊥) (v : τ → O)
    (heq : I.carrier = Submodule.span R (Set.range v)) (i : τ) :
    (BasisOfEqSpan B I hI v heq) i = v i := by simp only [BasisOfEqSpan, Basis.coe_mk]

/-- Certifies that `a ∉ I` given `R`-generators. -/
structure IdealNeMemCertificate [Algebra R O] {r : ℕ} (B : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin r → Fin r → R) (a : Fin r → R) where
  hieq : I.carrier = Submodule.span R (Set.range (fun i => B.equivFun.symm (v i)))
  ha : a ≠ 0
  d : R
  g : Fin r → R
  hmem : List.mulPointwise d (List.ofFn a) = List.sum
    (List.ofFn (fun k => List.mulPointwise (g k) (List.ofFn (v k))))
  i : Fin r
  hnedvd : ¬ d ∣ (g i)

/-- Correctness of `IdealNeMemCertificate`. -/
lemma ne_mem_of_certificate [IsDomain R] [IsPrincipalIdealRing R]
    [IsDomain O] [Algebra R O] {r : ℕ}
    (B : Basis (Fin r) R O) (I : Ideal O) (v : Fin r → Fin r → R)
    (a : Fin r → R) (A : IdealNeMemCertificate B I v a) :
    B.equivFun.symm a ∉ I := by
  by_cases hI : I = ⊥
  · rw [hI, Ideal.mem_bot]
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr A.ha
  · have hc := A.hmem
    rw [List.mulPointwise_ofFn] at hc
    let B' := BasisOfEqSpan B I hI (fun i => B.equivFun.symm (v i)) A.hieq
    have heqaux := table_sum_smul B v (A.d • a) (A.g) hc
    by_contra hmema
    have := Basis.dvd_coord_smul B' A.i ⟨B.equivFun.symm a, hmema⟩ A.d
    simp_rw [SetLike.mk_smul_of_tower_mk,
      ← LinearEquiv.map_smul B.equivFun.symm A.d a, heqaux] at this
    apply A.hnedvd
    convert this
    rw [Basis.coord_apply]
    nth_rw 1 [← Basis.repr_sum_self B' A.g]
    congr
    simp only [BasisOfEqSpan, Basis.coe_mk, B']
    rw [← Subtype.val_inj, Submodule.coe_sum]
    rfl

lemma ideal_mul_eq_span {ι τ : Type _} [Fintype ι] [Fintype τ]
    (v : ι → O) (w : τ → O)  :
    (Ideal.span (Set.range v)) * (Ideal.span (Set.range w)) =
    Ideal.span (Set.range (fun (⟨i,j⟩ : ι × τ) => (v i) * (w j) )) := by
    rw [Ideal.span_mul_span]
    congr
    ext x
    simp only [Set.mem_mul, Set.mem_range, exists_exists_eq_and, Prod.exists]

/-- Given `O`-generators for `I` and `J`, it certifies that `I * J ≤ ⟨w⟩` -/
structure IdealMulLeCertificate [Algebra R O] {r n m s : ℕ}
  (TT  : TimesTable (Fin r) R O) (I₁ I₂ : Ideal O)
  (u : Fin m → Fin r → R) (v : Fin n → Fin r → R) (w : Fin s → Fin r → R) where
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hI1 : I₁ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u i)))
  hI2 : I₂ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (v i)))
  M : Fin m → Fin n → Fin r → R -- products (u i) * (v j)
  hmul : ∀ i j, table_mul_list T (List.ofFn (u i)) (List.ofFn (v j)) = List.ofFn (M i j)
  g : Fin m → Fin n → Fin s → Fin r → R
  hle2 : ∀ i j, List.ofFn (M i j) = List.sum (List.ofFn
    (fun k => table_mul_list T (List.ofFn (g i j k)) (List.ofFn (w k))))

/-- Given `O`-generators for `I` and `J`, it certifies that `I * J = ⟨w⟩`. -/
structure IdealMulEqCertificate [Algebra R O] {r n m s : ℕ}
  (TT  : TimesTable (Fin r) R O) (I₁ I₂ : Ideal O)
  (u : Fin m → Fin r → R) (v : Fin n → Fin r → R) (w : Fin s → Fin r → R) extends IdealMulLeCertificate TT I₁ I₂ u v w where
  f : Fin s → Fin m → Fin n → Fin r → R
  hle1 : ∀ k , List.ofFn (w k) = List.sum (List.ofFn (fun i => List.sum
    (List.ofFn (fun j => table_mul_list T (List.ofFn (f k i j)) (List.ofFn (M i j) ) ))))

/-- Correctness of `IdealMulLeCertificate`.  -/
lemma ideal_eq_mul_of_IdealMulLeCertificate [Algebra R O] {r n m s : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {I₁ I₂ : Ideal O}
    {u : Fin m → Fin r → R} {v : Fin n → Fin r → R} {w : Fin s → Fin r → R}
    (A : IdealMulLeCertificate TT I₁ I₂ u v w) :
    I₁ * I₂ ≤ Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  have aux := A.hmul
  simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq] at aux
  have hmulaux :=
    fun i j => table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (aux i j).symm
  simp_rw [A.hI1, A.hI2, ideal_mul_eq_span, hmulaux]
  unfold Ideal.span
  refine (submodule_span_le_span_iff (S := O) (R := O) (O := O) _ _
      ((Submodule.span O (Set.range fun x
      ↦ TT.basis.equivFun.symm (w x))).carrier) rfl ?_ ).2 ?_
  · intro s x hx
    exact (Submodule.span O (Set.range fun i ↦ TT.basis.equivFun.symm (w i))).smul_mem' s hx
  · rintro ⟨i,j⟩
    use (fun k => TT.basis.equivFun.symm (A.g i j k))
    dsimp
    refine table_sum_mul TT.table TT.basis TT.basis_mul_basis _ _ _ ?_
    simp_rw [← table_mul_eq_table_mul' TT.table A.T A.heq]
    exact (A.hle2 i j)

/-- Correctness of `IdealMulEqCertificate`.  -/
lemma ideal_eq_mul_of_IdealMulEqCertificate [Algebra R O] {r n m s : ℕ} [NeZero r]
    (TT  : TimesTable (Fin r) R O) (I₁ I₂ : Ideal O)
    (u : Fin m → Fin r → R) (v : Fin n → Fin r → R) (w : Fin s → Fin r → R)
    (A : IdealMulEqCertificate TT I₁ I₂ u v w) :
    I₁ * I₂ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  have aux := A.hmul
  simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq] at aux
  have hmulaux :=
    fun i j => table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (aux i j).symm
  refine le_antisymm ?_ ?_
  · refine ideal_eq_mul_of_IdealMulLeCertificate (u := u) (v := v) (w := w) (TT := TT) ?_
    exact { T := A.T , heq := A.heq, hI1 := A.hI1 , hI2 := A.hI2
            M := A.M, hmul := A.hmul , g := A.g , hle2 := A.hle2}
  · simp_rw [A.hI1, A.hI2, ideal_mul_eq_span, hmulaux]
    refine (submodule_span_le_span_iff (S := O) _ _
      ((Submodule.span O (Set.range fun (x : Fin m × Fin n)
         ↦ TT.basis.equivFun.symm (A.M x.1 x.2))).carrier) rfl ?_).2 ?_
    · intro s x hx
      exact Submodule.smul_mem' _ s hx
    · intro k
      use (fun ⟨i,j⟩ => TT.basis.equivFun.symm (A.f k i j) )
      dsimp
      rw [Fintype.sum_prod_type]
      have aux := A.hle1 k
      let d : Fin m → Fin n → Fin r → R := fun i j => FnOfList r
        (table_mul_list' TT.table (List.ofFn (A.f k i j)) (List.ofFn (A.M i j)))
        (table_mul_list_length _ _ _)
      have hd : ∀ i j, List.ofFn (d i j) =
        table_mul_list' TT.table (List.ofFn (A.f k i j)) (List.ofFn (A.M i j)) :=
        fun i j ↦ listOfFn_of_FnOfList r _ (table_mul_list_length TT.table
          (List.ofFn (A.f k i j)) (List.ofFn (A.M i j)))
      have hmulaux2 := fun i j =>
        table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (hd i j)
      simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq, ← hd] at aux
      simp_rw [hmulaux2]
      exact table_sum_sum TT.basis _ _ aux

/- Purely computational version of `IdealMulLeCertificate'`. -/
structure IdealMulEqCertificate' {r n m s : ℕ} (T : Fin r → Fin r → List R)
  (u : Fin m → Fin r → R) (v : Fin n → Fin r → R) (w : Fin s → Fin r → R)  where
  M : Fin m → Fin n → Fin r → R -- products (u i) * (v j)
  hmul : ∀ i j, table_mul_list T (List.ofFn (u i)) (List.ofFn (v j)) = List.ofFn (M i j)
  f : Fin s → Fin m → Fin n → Fin r → R
  g : Fin m → Fin n → Fin s → Fin r → R
  hle1 : ∀ k , List.ofFn (w k) = List.sum (List.ofFn (fun i => List.sum
    (List.ofFn (fun j => table_mul_list T (List.ofFn (f k i j)) (List.ofFn (M i j) ) ))))
  hle2 : ∀ i j, List.ofFn (M i j) = List.sum (List.ofFn
    (fun k => table_mul_list T (List.ofFn (g i j k)) (List.ofFn (w k))))

/- Purely computational version of `IdealMulEqCertificate'`. -/
structure IdealMulLeCertificate' {r n m s : ℕ} (T : Fin r → Fin r → List R)
  (u : Fin m → Fin r → R) (v : Fin n → Fin r → R) (w : Fin s → Fin r → R)  where
  M : Fin m → Fin n → Fin r → R -- products (u i) * (v j)
  hmul : ∀ i j, table_mul_list T (List.ofFn (u i)) (List.ofFn (v j)) = List.ofFn (M i j)
  g : Fin m → Fin n → Fin s → Fin r → R
  hle2 : ∀ i j, List.ofFn (M i j) = List.sum (List.ofFn
    (fun k => table_mul_list T (List.ofFn (g i j k)) (List.ofFn (w k))))

/-- Correctness of `IdealMulEqCertificate'`.  -/
lemma ideal_eq_mul_of_IdealMulLeCertificate' [Algebra R O] {r n m s : ℕ} [NeZero r]
  {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
  (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {I₁ I₂ I₃ : Ideal O}
  {u : Fin m → Fin r → R} {v : Fin n → Fin r → R} {w : Fin s → Fin r → R}
  (hI1 : I₁ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u i))))
  (hI2 : I₂ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (v i))))
  (hI3 : I₃ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))))
  (A : IdealMulLeCertificate' T u v w) : I₁ * I₂ ≤ I₃ := by
  convert ideal_eq_mul_of_IdealMulLeCertificate (TT := TT) (I₁ := I₁) (I₂ := I₂)
    (u := u) (v := v) (w := w) ?_
  exact { T := T, heq := heq, hI1 := hI1
          hI2 := hI2,  M := A.M, hmul := A.hmul, g := A.g, hle2 := A.hle2 }

/-- Correctness of `IdealMulEqCertificate'`.  -/
lemma ideal_eq_mul_of_IdealMulEqCertificate' [Algebra R O] {r n m s : ℕ} [NeZero r]
  {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
  (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {I₁ I₂ I₃ : Ideal O}
  {u : Fin m → Fin r → R} {v : Fin n → Fin r → R} {w : Fin s → Fin r → R}
  (hI1 : I₁ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u i))))
  (hI2 : I₂ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (v i))))
  (hI3 : I₃ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))))
  (A : IdealMulEqCertificate' T u v w) : I₁ * I₂ = I₃ := by
  convert ideal_eq_mul_of_IdealMulEqCertificate TT I₁ I₂ u v w ?_
  exact { T := T, heq := heq, hI1 := hI1
          hI2 := hI2,  M := A.M, hmul := A.hmul, f := A.f
          g := A.g, hle1 := A.hle1, hle2 := A.hle2 }

lemma ideal_eq_prod_IdealMulEqCertificate' [Algebra R O] {r n : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {I : Fin (n + 1) → Ideal O}
    {m : Fin n → ℕ} {u : (i : Fin n) → Fin (m i) →  Fin r → R}
    {s : Fin (n + 1) → ℕ} {w : (i : Fin (n + 1)) → Fin (s i) →  Fin r → R}
    (heq1 : I 0 = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w 0 i))))
    (heq2 : ∀ (j : Fin n) , I j.succ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u j i))))
    (C : ∀ i : Fin n, IdealMulEqCertificate' T (w i.castSucc) (u i) (w (i.succ))) :
      ∏ j, I j = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w (Fin.last n) i))) := by
  induction n with
  | zero =>
    simp only [Nat.reduceAdd, Finset.univ_unique, Fin.default_eq_zero, Fin.isValue,
      Finset.prod_singleton, Fin.reduceLast]
    exact heq1
  | succ n h =>
    specialize h (I := fun i => I i.castSucc) (m := fun i => m i.castSucc)
      (u := fun i => u i.castSucc) (s := fun i => s i.castSucc) (w := fun i => w i.castSucc) heq1
      (fun i => heq2 i.castSucc) (fun i => C i.castSucc)
    rw [Fin.prod_univ_castSucc]
    refine ideal_eq_mul_of_IdealMulEqCertificate' heq h (heq2 (Fin.last n)) rfl (C (Fin.last n))

/- A chain of certificates for multiplications. -/
inductive IdealMulChainCertificate {R : Type*} [CommRing R] {r m : ℕ}
  (T : Fin r → Fin r → List R) (u : Fin m → Fin r → R) :
  {s : ℕ} → (Fin s → Fin r → R) → Type (u_4 + 1)
  | nil : IdealMulChainCertificate T u u
  | cons {x : ℕ} {v} {uu : Fin x → Fin r → R} {w} : IdealMulChainCertificate T u v →
    IdealMulEqCertificate' T v uu w → IdealMulChainCertificate T u w

/- A chain of certificates for containment of multiplications. -/
inductive IdealMulLeChainCertificate {R : Type*} [CommRing R] {r m : ℕ}
  (T : Fin r → Fin r → List R) (u : Fin m → Fin r → R) :
  {s : ℕ} → (Fin s → Fin r → R) → Type (u_4 + 1)
  | nil : IdealMulLeChainCertificate T u u
  | cons {x : ℕ} {v} {uu : Fin x → Fin r → R} {w} : IdealMulLeChainCertificate T u v →
    IdealMulLeCertificate' T v uu w → IdealMulLeChainCertificate T u w

/-- The intermediate ideals corresponding to a chain. -/
def IdealMulChainCertificate.Ideals [Algebra R O] {r m s : ℕ}
    (TT  : TimesTable (Fin r) R O)
    {T : Fin r → Fin r → List R} {u : Fin m → Fin r → R} {w : Fin s → Fin r → R} :
    (A : IdealMulChainCertificate T u w) → List (Ideal O)
  | nil => [Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u i)))]
  | cons (uu := uu) B _ => (B.Ideals TT) ++ [(Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (uu i))))]

/-- The intermediate ideals corresponding to a chain. -/
def IdealMulLeChainCertificate.Ideals [Algebra R O] {r m s : ℕ}
    (TT  : TimesTable (Fin r) R O)
    {T : Fin r → Fin r → List R} {u : Fin m → Fin r → R} {w : Fin s → Fin r → R} :
    (A : IdealMulLeChainCertificate T u w) → List (Ideal O)
  | nil => [Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u i)))]
  | cons (uu := uu) B _ => (B.Ideals TT) ++ [(Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (uu i))))]

notation "𝟙" => IdealMulChainCertificate.nil
infixl:65 " ⊗ " => IdealMulChainCertificate.cons

notation "𝕀" => IdealMulLeChainCertificate.nil
infixl:65 " ⊙ " => IdealMulLeChainCertificate.cons

lemma ideal_prod_of_IdealMulChainCertificate [Algebra R O] {r m s : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {u : Fin m → Fin r → R} {w : Fin s → Fin r → R}
    (A : IdealMulChainCertificate T u w) :
    List.prod (A.Ideals TT) = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  induction A with
  | nil => simp [IdealMulChainCertificate.Ideals]
  | cons A B hAB =>
    unfold IdealMulChainCertificate.Ideals
    rw [List.prod_append, hAB, List.prod_cons, List.prod_nil, mul_one]
    refine ideal_eq_mul_of_IdealMulEqCertificate' heq rfl rfl rfl B

lemma ideal_prod_of_IdealMulLeChainCertificate [Algebra R O] {r m s : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {u : Fin m → Fin r → R} {w : Fin s → Fin r → R}
    (A : IdealMulLeChainCertificate T u w) :
    List.prod (A.Ideals TT) ≤ Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  induction A with
  | nil => simp [IdealMulLeChainCertificate.Ideals]
  | cons A B hAB =>
    unfold IdealMulLeChainCertificate.Ideals
    rw [List.prod_append]
    simp only [List.prod_cons, List.prod_nil, Ideal.one_eq_top, Ideal.mul_top]
    expose_names
    refine le_trans (b := Ideal.span (Set.range fun i ↦ TT.basis.equivFun.symm (v i))
      * Ideal.span (Set.range fun i ↦ TT.basis.equivFun.symm (uu i))) ?_ ?_
    refine Ideal.mul_mono_left hAB
    refine ideal_eq_mul_of_IdealMulLeCertificate' heq rfl rfl rfl B

lemma ideal_eq_singleton_IdealMulChainCertificate [Algebra R O] {r m : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {u : Fin m → Fin r → R} {z : Fin r → R}
    {f : Fin 1 → Fin r → R} (hB : TT.basis.equivFun.symm z = 1) (p : ℕ) (hf : f 0 = p • z)
    (A : IdealMulChainCertificate T u f) :
      List.prod (A.Ideals TT) = Ideal.span {↑p} := by
    rw [ideal_prod_of_IdealMulChainCertificate heq A]
    congr
    ext j
    simp only [Set.mem_range, Set.mem_singleton_iff, Fin.exists_fin_one, Fin.isValue]
    rw [hf, ← Nat.cast_smul_eq_nsmul R p, LinearEquiv.map_smul , hB, Algebra.smul_def, mul_one]
    simp [eq_comm]

lemma ideal_le_singleton_IdealMulLeChainCertificate [Algebra R O] {r m : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {u : Fin m → Fin r → R} {z : Fin r → R}
    {f : Fin 1 → Fin r → R} (hB : TT.basis.equivFun.symm z = 1) (p : ℕ) (hf : f 0 = p • z)
    (A : IdealMulLeChainCertificate T u f) :
      List.prod (A.Ideals TT) ≤ Ideal.span {↑p} := by
    convert ideal_prod_of_IdealMulLeChainCertificate heq A
    ext j
    simp only [Set.mem_range, Set.mem_singleton_iff, Fin.exists_fin_one, Fin.isValue]
    rw [hf, ← Nat.cast_smul_eq_nsmul R p, LinearEquiv.map_smul , hB, Algebra.smul_def, mul_one]
    simp [eq_comm]

/- lemma ideal_ne_bot_IdealMulLeChainCertificate [Algebra R O] {r m s : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    {u : Fin m → Fin r → R} [hu : NeZero u] {w : Fin s → Fin r → R}
    (A : IdealMulLeChainCertificate T u w) : ∀ I ∈ (A.Ideals TT), I ≠ ⊥ := by
  intro I hI hc
  induction A with
  | nil =>
    unfold IdealMulLeChainCertificate.Ideals at hI
    simp only [ List.mem_cons, List.not_mem_nil, or_false] at hI
    rw [hI] at hc
    erw [Ideal.span_eq_bot] at hc
    have : ∀ i j , u i j = 0 := by
      intro i j
      specialize hc (TT.basis.equivFun.symm (u i))
      simp only [Set.mem_range, exists_apply_eq_apply,
      forall_const, (LinearEquiv.map_eq_zero_iff TT.basis.equivFun.symm)] at hc
      rw [hc]
      rfl
    exact hu.out (show u = 0 by ext ; rw [this] ; rfl)
  | cons A B hAB =>
    unfold IdealMulLeChainCertificate.Ideals at hI
    simp only [List.mem_append, List.mem_cons, List.not_mem_nil, or_false] at hI
    rcases hI with h1 | h2
    · contradiction
    · rw [hc] at h2
      symm at h2
      expose_names
      erw [Ideal.span_eq_bot] at h2
      have : ∀ i j , uu i j = 0 := by
        intro i j
        specialize h2 (TT.basis.equivFun.symm (uu i))
        simp only [Set.mem_range, exists_apply_eq_apply,
        forall_const, (LinearEquiv.map_eq_zero_iff TT.basis.equivFun.symm)] at h2
        rw [h2]
        rfl
      exact inst_4.out (show uu = 0 by ext ; rw [this] ; rfl) -/

lemma ideal_eq_singleton_IdealMulEqCertificate' [Algebra R O] {r n : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    (heq : ∀ i j , T i j = List.ofFn (TT.table i j)) {I : Fin (n + 1) → Ideal O}
    {m : Fin n → ℕ} {u : (i : Fin n) → Fin (m i) →  Fin r → R}
    {s : Fin (n + 1) → ℕ} [NeZero (s (Fin.last n))] {w : (i : Fin (n + 1)) → Fin (s i) →  Fin r → R}
    (heq1 : I 0 = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w 0 i))))
    (heq2 : ∀ (j : Fin n) , I j.succ = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u j i))))
    (C : ∀ i : Fin n, IdealMulEqCertificate' T (w i.castSucc) (u i) (w (i.succ)))
    {z : Fin r → R} (hB : TT.basis.equivFun.symm z = 1) (p : ℕ)
    (hp : w (Fin.last n) = fun _ => p • z) :
      ∏ j, I j = Ideal.span {↑p} := by
    rw [ideal_eq_prod_IdealMulEqCertificate' heq heq1 heq2 C, hp]
    congr
    ext j
    simp only [Set.mem_range, Set.mem_singleton_iff, exists_const]
    rw [← Nat.cast_smul_eq_nsmul R p, LinearEquiv.map_smul , hB, Algebra.smul_def, mul_one]
    simp [eq_comm]

/-- Given `O`-generators for `I` and `a ∈ O`, certifies generators for `⟨a⟩ * I`. -/
structure IdealMulPrincipalCertificate [Algebra R O] {r m : ℕ}
  (TT  : TimesTable (Fin r) R O) (I : Ideal O)
  (α : Fin r → R) (u : Fin m → Fin r → R) (w : Fin m → Fin r → R) where
  T : Fin r → Fin r → List R
  heq : ∀ i j , T i j = List.ofFn (TT.table i j)
  hI : I = Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (u i)))
  hmul : ∀ i, table_mul_list T (List.ofFn α) (List.ofFn (u i)) = List.ofFn (w i)

/-- Correctness of  `IdealMulPrincipalCertificate`. -/
lemma  ideal_eq_principal_mul_of_IdealMulPrincipalCertificate [Algebra R O] {r m : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {I : Ideal O}
    {α : Fin r → R} {u : Fin m → Fin r → R} {w : Fin m → Fin r → R}
    (A : IdealMulPrincipalCertificate TT I α u w) :
      Ideal.span {(TT.basis).equivFun.symm α} * I =
        Ideal.span (Set.range (fun i => (TT.basis).equivFun.symm (w i))) := by
  have aux := A.hmul
  simp_rw [table_mul_eq_table_mul' TT.table A.T A.heq] at aux
  rw [A.hI, Ideal.span_mul_span]
  congr
  have : (fun i ↦ TT.basis.equivFun.symm (w i)) =
    fun x ↦ TT.basis.equivFun.symm α * TT.basis.equivFun.symm (u x) := by
    ext i
    exact (table_mul_list_eq_mul TT.table TT.basis _ _ _ TT.basis_mul_basis (aux i).symm).symm
  rw [this]
  ext x
  simp only [Set.mem_mul, Set.mem_range, Set.mem_singleton_iff, Set.mem_range]
  simp only [↓existsAndEq, Basis.equivFun_symm_apply, true_and]

/-- `IsInClass x I` expresses that `I` is in the same ideal class as `∏ i, x i`. -/
def IsInClass (R : Type*) {n : ℕ} [CommRing R] (x : Fin n → Ideal R) :
    Ideal R → (Fin n → ℕ) → Prop := by
  intro I m
  exact ∃ (α : R) (β : R) , ∃ (_ : α ≠ 0) (_ : β ≠ 0),
    Ideal.span {α} * I = Ideal.span {β} * ∏ j, x j ^ (m j)

-- Prove element is nonzero from proof coordinates are not zero:
-- (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr hv

lemma ideal_mem_principal_class [Algebra R O] {r : ℕ} [NeZero r] (B : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin r → R) (hv : v ≠ 0)
    (hI : I = Ideal.span (Set.range (fun _ : Fin 1 => B.equivFun.symm v))) :
    ∃ (α β : O), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
      Ideal.span {α} * I = Ideal.span {β} := by
  use 1 , B.equivFun.symm v
  have haux : B.equivFun.symm v ≠ 0 := (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr hv
  have : Nontrivial O := nontrivial_of_ne (B.equivFun.symm v) 0 haux
  use (zero_ne_one' O).symm , haux
  simp only [Ideal.span_singleton_one, Ideal.top_mul]
  convert hI
  simp only [Basis.equivFun_symm_apply, Set.range_const]

lemma ideal_mem_principal_class'
    [Algebra R O] {r : ℕ} [NeZero r] (B : Basis (Fin r) R O)
    (I : Ideal O) {J : Ideal O} (v : Fin r → R) (hv : v ≠ 0)
    (hI : I = Ideal.span (Set.range (fun i : Fin 1 => B.equivFun.symm (![v] i) ))) :
    ∃ (α β : O), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
      Ideal.span {α} * I = Ideal.span {β} * J ^ 0 := by
  convert ideal_mem_principal_class (r := r) B I v hv ?_
  · simp only [pow_zero, Ideal.one_eq_top, Ideal.mul_top]
  · rw [hI]
    refine congrArg _ ?_
    simp only [Matrix.cons_val_fin_one, Basis.equivFun_symm_apply, Set.range_const]

lemma ideal_mem_principal_class'' {O R: Type*} [CommRing O] [CommRing R]
  [Algebra R O] {r : ℕ} [NeZero r] (B : Basis (Fin r) R O)
  (I : Ideal O) (v : Fin r → R) (hv : v ≠ 0)
  (hI : I = Ideal.span (Set.range (fun i : Fin 1 => B.equivFun.symm (![v] i) ))) :
  ∃ (α β : O), ∃ (_ : α ≠ 0), ∃ (_ : β ≠ 0),
    Ideal.span {α} * I = Ideal.span {β} := by
  refine ideal_mem_principal_class (r := r) B I v hv ?_
  · rw [hI]
    refine congrArg _ ?_
    simp only [Matrix.cons_val_fin_one, Basis.equivFun_symm_apply, Set.range_const]

/-- Given `O`-generators for `I` and `r ∈ R`, certifies generators for `⟨r⟩ · I`. -/
lemma ideal_mul_span_singleton_coe [Algebra R O] {r m : ℕ} [NeZero r] (B : Basis (Fin r) R O)
    (I : Ideal O) (v : Fin m → Fin r → R)
    (hI : I = Ideal.span (Set.range (fun i => B.equivFun.symm (v i)))) (r : R) :
    Ideal.span {(algebraMap R O r)} * I =
      Ideal.span (Set.range (fun i => B.equivFun.symm ((r • v) i))) := by
  rw [hI, Ideal.span_mul_span] ; congr
  ext x
  simp only [Set.mem_mul, Set.mem_range, Set.mem_singleton_iff, Set.mem_range,
    ↓existsAndEq, Basis.equivFun_symm_apply, true_and, Pi.smul_apply, map_smul]
  simp_rw [Algebra.smul_def]

lemma ideal_span_ne_bot [Algebra R O] {r m : ℕ} {B : Basis (Fin r) R O}
    (i : Fin m) (j : Fin r) {v : Fin m → Fin r → R} (hv : v i j ≠ 0) :
   Ideal.span (Set.range (fun i => B.equivFun.symm (v i))) ≠ 0 := by
    intro hc
    erw [Ideal.span_eq_bot] at hc
    specialize hc (B.equivFun.symm (v i))
    simp only [Set.mem_range, exists_apply_eq_apply,
      forall_const, (LinearEquiv.map_eq_zero_iff B.equivFun.symm)] at hc
    rw [hc] at hv
    simp only [Pi.zero_apply, ne_eq, not_true_eq_false] at hv

/- Certify `⟨s⟩ * I = ⟨a⟩ * J`, where `s` is a scalar. Purely computational: -/
structure RelationCertificate {r n m : ℕ} (T : Fin r → Fin r → List R)
  (s : R) (u : Fin m → Fin r → R) (a : Fin r → R) (v : Fin n → Fin r → R)  where
  su : Fin m → Fin r → R
  hsu : s • u = su
  w : Fin n → Fin r → R
  hw : ∀ i, table_mul_list T (List.ofFn a) (List.ofFn (v i)) = List.ofFn (w i)
  g : Fin m → Fin n → Fin r → R
  h : Fin n → Fin m → Fin r → R
  hle1 : ∀ i, List.ofFn (su i) =
    List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (g i k)) (List.ofFn (w k))))
  hle2 : ∀ i, List.ofFn (w i) =
    List.sum (List.ofFn (fun k => table_mul_list T  (List.ofFn (h i k)) (List.ofFn (su k))))

lemma relation_of_RelationCertificate [Algebra R O] {r m n : ℕ} [NeZero r]
    {TT  : TimesTable (Fin r) R O} {T : Fin r → Fin r → List R}
    (heq : ∀ i j , T i j = List.ofFn (TT.table i j))
    {I J : Ideal O} {s : R} {u : Fin m → Fin r → R} {a : Fin r → R} {v : Fin n → Fin r → R}
    (hieq1 : I = Ideal.span (Set.range (fun i => TT.basis.equivFun.symm (u i))))
    (hieq2 : J = Ideal.span (Set.range (fun j => TT.basis.equivFun.symm (v j))))
    (C : RelationCertificate T s u a v) :
    (Ideal.span {algebraMap R O s}) * I = Ideal.span {TT.basis.equivFun.symm a} * J := by
  rw [ideal_mul_span_singleton_coe TT.basis I u hieq1, C.hsu,
    ideal_eq_principal_mul_of_IdealMulPrincipalCertificate
    (TT := TT) (I := J) (α := a) (u := v) (w := C.w)]
  swap
  exact { T := T, heq := heq, hI := hieq2, hmul := C.hw }
  refine ideal_eq_of_IdealEqCertificateO' heq rfl rfl ?_
  exact { g := C.g, h := C.h, hle1 := C.hle1, hle2 := C.hle2}





end I
