import IdealArithmetic.Examples.NF6_4_19208000_1.ClassGroupSaturated6_4_19208000_1_2
import IdealArithmetic.Examples.NF6_4_19208000_1.RelationIdeals6_4_19208000_1F0
import IdealArithmetic.Examples.NF6_4_19208000_1.RelationIdeals6_4_19208000_1F1
import IdealArithmetic.Examples.NF6_4_19208000_1.RelationIdeals6_4_19208000_1F2
import IdealArithmetic.Examples.NF6_4_19208000_1.PrimesBelowCert6_4_19208000_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with α root of polynomial `X^6 - 5*X^4 - 50*X^2 + 125`.
Class group structure `[2]`, generated by class of ideals `[(7, a + 2)]`. -/

/- Ring of integers with basis `[1, a, 1/5*a^2, 1/5*a^3, 1/25*a^4, 1/25*a^5]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 6 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [5]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateWLists K 5 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M5
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [5] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']

theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl

instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O

def SturmRC : SturmBuilderOfList [[125, 0, -50, 0, -5, 0, 1], [0, -100, 0, -20, 0, 6], [-4500, 0, 1200, 0, 60], [0, -35000, 0, 14000], [245000000, 0, -73500000], [0, -321562500000], [-4689453125000000]] [125, 0, -50, 0, -5, 0, 1] [0, -100, 0, -20, 0, 6] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 6 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [36, 3600, 196000000, 5402250000000000, 103402441406250000000000]
  f := [1, 36, 3600, 196000000, 5402250000000000]
  epos := by decide
  fpos := by decide
  Q := [[0, 6], [0, 360], [0, 840000], [0, -1029000000000], [0, 23634843750000000000]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^6 - 5*X^4 - 50*X^2 + 125
  l := [125, 0, -50, 0, -5, 0, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[125, 0, -50, 0, -5, 0, 1], [0, -100, 0, -20, 0, 6], [-4500, 0, 1200, 0, 60], [0, -35000, 0, 14000], [245000000, 0, -73500000], [0, -321562500000], [-4689453125000000]]
  SB := SturmRC
  k := 4
  r := 5
  hr := by decide
  hreq := by decide

def NPCU2 : pMaximalUnitsCertificateDvdT O 2 where
 hp := by decide
 r := 4
 huc := by
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2, zeta3, zeta4]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
  | 2 => isUnit_zeta3
  | 3 => isUnit_zeta4
 v := v'
 m := 2
 hm := by norm_num
 hmv := v_pow_one
 t := 6
 hrle := by decide
 q := ![7, 13, 13, 13, 13, 29]
 hqP := by
  intro i
  match i with
  | 0 => exact Sat2.hq7
  | 1 => exact Sat2.hq13
  | 2 => exact Sat2.hq13
  | 3 => exact Sat2.hq13
  | 4 => exact Sat2.hq13
  | 5 => exact Sat2.hq29
 I := ![Sat2.I0, Sat2.I1, Sat2.I2, Sat2.I3, Sat2.I4, Sat2.I5]
 hcard := fun i =>
  match i with
  | 0 => Sat2.N0
  | 1 => Sat2.N1
  | 2 => Sat2.N2
  | 3 => Sat2.N3
  | 4 => Sat2.N4
  | 5 => Sat2.N5
 ζ := ![3, 2, 2, 2, 2, 2]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf Sat2.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat2.R13) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat2.R13) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf Sat2.R13) ▸ IsPrimitiveRoot.orderOf _)
  | 4 => ((orderOf_of_IsOrderOf Sat2.R13) ▸ IsPrimitiveRoot.orderOf _)
  | 5 => ((orderOf_of_IsOrderOf Sat2.R29) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 M := ![![0, 1, 1, 0, 1], ![1, 0, 0, 1, 0], ![1, 0, 1, 1, 0], ![0, 1, 0, 1, 0], ![0, 1, 1, 0, 0], ![1, 1, 0, 1, 0]]
 hM1 := by
  intro i j hj
  fin_cases i <;> interval_cases j
  · erw [eq_of_DiscreteLogCertificate Sat2.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log02] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log03] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log12] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log13] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log21] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log22] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log23] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log30] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log31] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log32] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log33] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log40] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log41] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log42] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log43] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log50] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log51] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log52] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log53] ; decide
 hM2 := by
  intro i
  fin_cases i
  · erw [eq_of_DiscreteLogCertificate Sat2.Log04] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log14] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log24] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log34] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log44] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log54] ; decide
 Minv := ![![0, 0, 1, 1, 1], ![0, 1, 1, 0, 1], ![0, 1, 1, 0, 0], ![0, 1, 1, 1, 1], ![1, 0, 0, 0, 1]]
 hInv := by decide

def NPSU2 : pSaturatedClassGroupCertificateDvdT 2 ![J0] ![2] where
 topMaximalUnitsCertificateDvdT := NPCU2
 a := ![alpha0]
 γ := 1
 hc := by decide
 ψ := ![0]
 iψ := ![0]
 hψ := by decide
 hψn := by
  intro i
  fin_cases i
  · decide
 h := fun i =>
  match i with
  | 0 => J0_pow2
 N := ![![0], ![0], ![1], ![0], ![0], ![0]]
 hM3 := by
  intro (i : Fin 6) j
  match i , j with
  | 0, 0 => exact Sat2.Log05
  | 1, 0 => exact Sat2.Log15
  | 2, 0 => exact Sat2.Log25
  | 3, 0 => exact Sat2.Log35
  | 4, 0 => exact Sat2.Log45
  | 5, 0 => exact Sat2.Log55
 hDl := by decide
 NInv := ![![0, 0, 0, 1, 0, 1], ![0, 1, 0, 0, 0, 1], ![0, 1, 0, 0, 1, 1], ![0, 1, 0, 1, 0, 1], ![1, 0, 0, 0, 1, 0], ![0, 0, 1, 0, 1, 1]]
 hN := by decide

lemma T_discr : T.discr = -4689453125000000 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  · rw [T_ofList]
  · decide


theorem K_discr : NumberField.discr K = -19208000 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 1 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : MinkowskiBound K ≤ (86.12448056158439 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √19208000 ≤ 4382.693246 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 0.015432098765432098 * √19208000 ≤ 67.644155 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}

def e := ![9, 6, 6]
def s := ![9, 9, 5]

def g : (i : Fin 3) → Fin (e i) → Ideal O := by
  rintro ⟨i, hi⟩
  interval_cases i
  exact ![I2N0, I3N0, I3N1, I7N0, I7N1, I13N0, I13N1, I13N2, I13N3]
  exact ![I29N1, I29N2, I41N2, I41N3, I43N1, I43N2]
  exact ![I71N1, I71N2, I71N3, I71N4, I83N0, I83N1]

def BM : (i : Fin 3) → Fin (e i) → (Fin 1 → ℕ) := by
  rintro ⟨i, hi⟩
  interval_cases i
  exact ![![1], ![1], ![1], ![1], ![1], ![1], ![1], ![1], ![1]]
  exact ![![0], ![0], ![0], ![0], ![1], ![1]]
  exact ![![0], ![0], ![0], ![0], ![1], ![1]]

lemma primesGenerationAux0  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 0)) => PB87.Il ((indexPair_inv s) ⟨0,x⟩))).flatten ↔ y ∈ List.ofFn (g 0) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I2N0, I2N0, I3N0, I3N1, I7N0, I7N0, I7N0, I7N1, I7N1, I7N1, I13N0, I13N1, I13N2, I13N3] ↔ y ∈ [I2N0, I3N0, I3N1, I7N0, I7N1, I13N0, I13N1, I13N2, I13N3]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

lemma primesGenerationAux1  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 1)) => PB87.Il ((indexPair_inv s) ⟨1,x⟩))).flatten ↔ y ∈ List.ofFn (g 1) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I29N1, I29N2, I41N2, I41N3, I43N1, I43N2] ↔ y ∈ [I29N1, I29N2, I41N2, I41N3, I43N1, I43N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

lemma primesGenerationAux2  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 2)) => PB87.Il ((indexPair_inv s) ⟨2,x⟩))).flatten ↔ y ∈ List.ofFn (g 2) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I71N1, I71N2, I71N3, I71N4, I83N0, I83N1] ↔ y ∈ [I71N1, I71N2, I71N3, I71N4, I83N0, I83N1]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

lemma primesGenerationAux {x} : x ∈ (List.ofFn PB87.Il).flatten ↔ x ∈ List.ofFn (Fin.addCasesIter e g) := by
  refine (list_flatten_eq_list_addCasesIter g (s := s) PB87.Il ?_ x)
  rintro ⟨i, hi⟩ x
  interval_cases i

  · exact primesGenerationAux0
  · exact primesGenerationAux1
  · exact primesGenerationAux2

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 87} ⊆ Set.range (Fin.addCasesIter e g) :=
  le_primes_below_bound_of_PrimesBelowBoundCertificate_le' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv ((Fin.addCasesIter e g)) PB87 (fun _ hx => primesGenerationAux.1 hx)

def g' : Fin 21 → nonZeroDivisors (Ideal O) := by
  intro i
  have : (Fin.addCasesIter e g) i ∈ (List.ofFn PB87.Il).flatten := by
    simp only [primesGenerationAux, List.mem_ofFn, exists_apply_eq_apply]
  exact Ideal.toNonZeroDivisorOfNeZero ((Fin.addCasesIter e g) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate' _ PB87) (hc ▸ this) ))

def x : Fin 1 → Ideal O := ![J0]

def x' :  Fin 1 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (x i) (?_ )
  unfold x
  fin_cases i
  · exact ideal_span_ne_bot 0 0 (by decide)

lemma g'_apply : ∀ (i : Fin 21), ↑(g' i) = (Fin.addCasesIter e g) i := by
  intro i
  rfl

lemma x'_apply : ∀ (i : Fin 1), ↑(x' i) = x i := by
  intro i
  rfl

/-- v4.32 helper. Proven in a clean *generic* `[CommRing A]` context, where `simp`
reduces the all-`^0` product to `1`. Inside this file the local instances stop
`simp`/`rw` from firing `pow_zero`/`mul_one` on the goal's product directly, so the
all-zero-exponent `IsInClass` bullets multiply through this instead (matched by
`Eq.trans` up to defeq). -/
private lemma span_eq_span_mul_prod_zero₁ {A : Type*} [CommRing A] (β : A) (a : Ideal A) :
    Ideal.span {β} = Ideal.span {β} * (1 * a ^ 0) := by simp

lemma relations_proof0 (i : Fin 9) : IsInClass O x (g 0 i) (BM 0 i) := by
  show IsInClass O x (g 0 i) (![![1], ![1], ![1], ![1], ![1], ![1], ![1], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · erw [one_mul]
    use 7 , B.equivFun.symm ![-11, 9, -4, 2, 6, -3] ,
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R2N0
  · erw [one_mul]
    use 7, B.equivFun.symm ![11, -2, -3, -2, -6, 3],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R3N0
  · erw [one_mul]
    use 7, B.equivFun.symm ![-5, 6, 2, -1, 4, -2],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R3N1
  · erw [one_mul]
    use 1, B.equivFun.symm ![1, 0, 0, 0, 0, 0],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R7N0
  · erw [one_mul]
    use 7, B.equivFun.symm ![-17, -9, -3, -2, 8, 3],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R7N1
  · erw [one_mul]
    use 7, B.equivFun.symm ![-1, -3, -1, -3, 5, 1],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R13N0
  · erw [one_mul]
    use 7, B.equivFun.symm ![-12, 6, 2, -1, 4, -2],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R13N1
  · erw [one_mul]
    use 7, B.equivFun.symm ![-2, -6, -2, 1, 3, 2],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R13N2
  · erw [one_mul]
    use 7, B.equivFun.symm ![13, -3, -1, -3, -9, 1],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R13N3

lemma relations_proof1 (i : Fin 6) : IsInClass O x (g 1 i) (BM 1 i) := by
  show IsInClass O x (g 1 i) (![![0], ![0], ![0], ![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · erw [one_mul]
    convert ideal_mem_principal_class'' B _ _ ?_ rfl
    rfl ; erw [mul_one] ; decide
  · erw [one_mul]
    convert ideal_mem_principal_class'' B _ _ ?_ rfl
    rfl ; erw [mul_one] ; decide
  · erw [one_mul]
    convert ideal_mem_principal_class'' B _ _ ?_ rfl
    rfl ; erw [mul_one] ; decide
  · erw [one_mul]
    convert ideal_mem_principal_class'' B _ _ ?_ rfl
    rfl ; erw [mul_one] ; decide
  · erw [one_mul]
    use 7, B.equivFun.symm ![-11, 9, 3, 2, 6, -3],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R43N1
  · erw [one_mul]
    use 7, B.equivFun.symm ![-10, -2, -3, -2, 8, 3],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R43N2

lemma relations_proof2 (i : Fin 6) : IsInClass O x (g 2 i) (BM 2 i) := by
  show IsInClass O x (g 2 i) (![![0], ![0], ![0], ![0], ![1], ![1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · erw [one_mul]
    convert ideal_mem_principal_class'' B _ _ ?_ rfl
    rfl ; erw [mul_one] ; decide
  · erw [one_mul]
    convert ideal_mem_principal_class'' B _ _ ?_ rfl
    rfl ; erw [mul_one] ; decide
  · erw [one_mul]
    convert ideal_mem_principal_class'' B _ _ ?_ rfl
    rfl ; erw [mul_one] ; decide
  · erw [one_mul]
    convert ideal_mem_principal_class'' B _ _ ?_ rfl
    rfl ; erw [mul_one] ; decide
  · erw [one_mul]
    use 7, B.equivFun.symm ![19, 15, 5, 1, -11, -5],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R83N0
  · erw [one_mul]
    use 7, B.equivFun.symm ![4, -9, -3, -2, 1, 3],
    (by refine Nat.cast_ne_zero.2 (by decide)) , (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
    exact R83N1

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      g'_apply x'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop g BM (IsInClass O x) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2

def ClassGroupO_equiv : (∀ i : Fin 1 , (ZMod (![2] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 1), NeZero (![2] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate x'_apply NPSU2.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![2] i = ∏ i, (![2] i) ^ (![1] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [2] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![2]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 2
  simp_rw [h] ; left
  exact NPSU2
  omega

def class_group_equiv : (∀ i : Fin 1 , (ZMod (![2] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_2 : NumberField.classNumber K = 2 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
