import IdealArithmetic.Examples.NF5_1_3790297_2.ClassGroupSaturated5_1_3790297_2_2
import IdealArithmetic.Examples.NF5_1_3790297_2.RelationIdeals5_1_3790297_2F0
import IdealArithmetic.Examples.NF5_1_3790297_2.RelationIdeals5_1_3790297_2F1
import IdealArithmetic.Examples.NF5_1_3790297_2.RelationIdeals5_1_3790297_2F2
import IdealArithmetic.Examples.NF5_1_3790297_2.RelationIdeals5_1_3790297_2F3
import IdealArithmetic.Examples.NF5_1_3790297_2.PrimesBelowCert5_1_3790297_2
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with with α root of polynomial `X^5 - X^4 + 3*X^2 + 21*X + 4`.
Class group structure `[2, 2]`, generated by class of ideals `[(2, a), (2, -1/4*a^4 + 1/2*a^3 - 1/2*a^2 - 5/4*a - 3)]`. -/

/- Ring of integers with basis `[1, a, a^2, a^3, 1/16*a^4 + 1/8*a^3 + 3/8*a^2 + 5/16*a + 1/4]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible 

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

-- These instances were not needed previously. Additional in this new Lean/Mathlib version 
instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 5 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out 

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ [2]
  · fin_cases hc
    exact @pMaximal_of_MaximalOrderCertificateOfUnramifiedLists K 2 _ IsAddTorsionFree.to_noZeroSMulDivisors_int _ O Om hm _ _ M2
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [2] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl



instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B 

-- Additional in this new Lean/Mathlib version 
instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O


def SturmRC : SturmBuilderOfList [[4, 21, 3, 0, -1, 1], [21, 6, 0, -4, 5], [-121, -426, -45, 4], [-1025, -3662, -717], [882434, 3134138], [970316032]] [4, 21, 3, 0, -1, 1] [21, 6, 0, -4, 5] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic 
    have hi : i < 5 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [25, 16, 514089, 9822821003044]
  f := [1, 25, 16, 514089]
  epos := by decide
  fpos := by decide
  Q := [[-1, 5], [209, 20], [46913, -2868], [-10844508178, -2247176946]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^5 - X^4 + 3*X^2 + 21*X + 4
  l := [4, 21, 3, 0, -1, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[4, 21, 3, 0, -1, 1], [21, 6, 0, -4, 5], [-121, -426, -45, 4], [-1025, -3662, -717], [882434, 3134138], [970316032]]
  SB := SturmRC
  k := 1
  r := 3
  hr := by decide
  hreq := by decide 

def NPCU2 : pMaximalUnitsCertificateDvdT O 2 where 
 hp := by decide
 r := 2
 huc := by 
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2]
 hu := fun i => 
  match i with 
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
 v := v
 m := 2
 hm := by norm_num
 hmv := v_pow_one
 t := 5
 hrle := by decide
 q := ![7, 11, 17, 37, 37]
 hqP := by 
  intro i 
  match i with 
  | 0 => exact Sat2.hq7
  | 1 => exact Sat2.hq11
  | 2 => exact Sat2.hq17
  | 3 => exact Sat2.hq37
  | 4 => exact Sat2.hq37
 I := ![Sat2.I0, Sat2.I1, Sat2.I2, Sat2.I3, Sat2.I4]
 hcard := fun i =>
  match i with  
  | 0 => Sat2.N0
  | 1 => Sat2.N1
  | 2 => Sat2.N2
  | 3 => Sat2.N3
  | 4 => Sat2.N4
 ζ := ![3, 2, 3, 2, 2]
 hr := fun i =>
  match i with 
  | 0 => ((orderOf_of_IsOrderOf Sat2.R7) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat2.R11) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat2.R17) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf Sat2.R37) ▸ IsPrimitiveRoot.orderOf _)
  | 4 => ((orderOf_of_IsOrderOf Sat2.R37) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 M := ![![1, 1, 1], ![1, 0, 1], ![1, 0, 0], ![1, 1, 0], ![0, 0, 0]]
 hM1 := by 
  intro i j hj
  fin_cases i <;> interval_cases j 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log21] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log30] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log31] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log40] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log41] ; decide
 hM2 := by 
  intro i 
  fin_cases i 
  · erw [eq_of_DiscreteLogCertificate Sat2.Log02] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log12] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log22] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log32] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat2.Log42] ; decide
 Minv := ![![0, 0, 1], ![1, 1, 0], ![0, 1, 1]]
 hInv := by decide

def NPSU2 : pSaturatedClassGroupCertificateDvdT 2 ![J0, J1] ![2, 2] where 
 topMaximalUnitsCertificateDvdT := NPCU2
 a := ![alpha0,alpha1]
 γ := 2
 hc := by decide
 ψ := ![0, 1]
 iψ := ![0, 1] 
 hψ := by decide 
 hψn := by 
  intro i 
  fin_cases i 
  · decide
  · decide
 h := fun i =>
  match i with 
  | 0 => by convert J0_pow2
  | 1 => by convert J1_pow2
 N := ![![0, 1], ![0, 0], ![0, 1], ![1, 0], ![1, 1]]
 hM3 := by 
  intro (i : Fin 5) j
  match i , j with 
  | 0, 0 => exact Sat2.Log03
  | 0, 1 => exact Sat2.Log04
  | 1, 0 => exact Sat2.Log13
  | 1, 1 => exact Sat2.Log14
  | 2, 0 => exact Sat2.Log23
  | 2, 1 => exact Sat2.Log24
  | 3, 0 => exact Sat2.Log33
  | 3, 1 => exact Sat2.Log34
  | 4, 0 => exact Sat2.Log43
  | 4, 1 => exact Sat2.Log44
 hDl := by decide 
 NInv := ![![1, 1, 0, 1, 1], ![0, 0, 1, 1, 1], ![1, 0, 0, 1, 1], ![1, 1, 1, 1, 0], ![1, 1, 1, 1, 1]]
 hN := by decide 

lemma T_discr : T.discr = 970316032 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]

theorem K_discr : NumberField.discr K = 3790297 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 2 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : MinkowskiBound K ≤ (121.2059430881243 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √3790297 ≤ 1946.8685209999999 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 24/625 * √3790297 ≤ 74.769751 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}


def e := ![10, 10, 12, 2]
def s := ![9, 9, 9, 3]
def g : (i : Fin 4) → Fin (e i) → Ideal O := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![I2N0, I2N1, I2N2, I5N0, I7N0, I7N1, I11N0, I11N1, I11N2, I17N1]
  exact ![I37N1, I37N2, I37N3, I41N1, I43N1, I53N1, I59N1, I59N2, I61N1, I61N2]
  exact ![I67N2, I71N1, I79N1, I83N1, I89N1, I89N2, I89N3, I97N2, I101N1, I101N2, I103N1, I103N2]
  exact ![I113N1, I113N2]

def BM : (i : Fin 4) → Fin (e i) → (Fin 2 → ℕ) := by 
  rintro ⟨i, hi⟩ 
  interval_cases i 
  exact ![![1, 0], ![0, 1], ![1, 1], ![1, 0], ![1, 1], ![1, 1], ![1, 0], ![1, 1], ![0, 1], ![0, 1]]
  exact ![![1, 0], ![0, 0], ![1, 0], ![1, 0], ![1, 1], ![0, 1], ![1, 1], ![0, 0], ![1, 0], ![1, 0]]
  exact ![![1, 0], ![1, 1], ![0, 1], ![1, 1], ![1, 1], ![1, 1], ![0, 1], ![0, 1], ![0, 1], ![1, 0], ![1, 0], ![0, 1]]
  exact ![![0, 1], ![1, 0]]

lemma primesGenerationAux0  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 0)) => PB122.Il ((indexPair_inv s) ⟨0,x⟩))).flatten ↔ y ∈ List.ofFn (g 0) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I2N0, I2N1, I2N2, I5N0, I7N0, I7N1, I7N1, I7N1, I11N0, I11N1, I11N2, I17N1] ↔ y ∈ [I2N0, I2N1, I2N2, I5N0, I7N0, I7N1, I11N0, I11N1, I11N2, I17N1]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

  
lemma primesGenerationAux1  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 1)) => PB122.Il ((indexPair_inv s) ⟨1,x⟩))).flatten ↔ y ∈ List.ofFn (g 1) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I37N1, I37N2, I37N3, I41N1, I43N1, I53N1, I59N1, I59N2, I61N1, I61N2] ↔ y ∈ [I37N1, I37N2, I37N3, I41N1, I43N1, I53N1, I59N1, I59N2, I61N1, I61N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

  
lemma primesGenerationAux2  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 2)) => PB122.Il ((indexPair_inv s) ⟨2,x⟩))).flatten ↔ y ∈ List.ofFn (g 2) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I67N2, I71N1, I79N1, I83N1, I89N1, I89N2, I89N3, I97N2, I101N1, I101N2, I103N1, I103N1, I103N2] ↔ y ∈ [I67N2, I71N1, I79N1, I83N1, I89N1, I89N2, I89N3, I97N2, I101N1, I101N2, I103N1, I103N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

  
lemma primesGenerationAux3  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 3)) => PB122.Il ((indexPair_inv s) ⟨3,x⟩))).flatten ↔ y ∈ List.ofFn (g 3) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I113N1, I113N2] ↔ y ∈ [I113N1, I113N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]

  
lemma primesGenerationAux {x} : x ∈ (List.ofFn PB122.Il).flatten ↔ x ∈ List.ofFn (Fin.addCasesIter e g) := by
  refine (list_flatten_eq_list_addCasesIter g (s := s) PB122.Il ?_ x)
  rintro ⟨i, hi⟩ x
  interval_cases i 
  · exact primesGenerationAux0
  · exact primesGenerationAux1
  · exact primesGenerationAux2
  · exact primesGenerationAux3

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 122} ⊆ Set.range (Fin.addCasesIter e g) := 
  le_primes_below_bound_of_PrimesBelowBoundCertificate_le' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv ((Fin.addCasesIter e g)) PB122 (fun _ hx => primesGenerationAux.1 hx)

def g' : Fin 34 → nonZeroDivisors (Ideal O) := by
  intro i
  have : (Fin.addCasesIter e g) i ∈ (List.ofFn PB122.Il).flatten := by 
    simp only [primesGenerationAux, List.mem_ofFn, exists_apply_eq_apply]
  exact Ideal.toNonZeroDivisorOfNeZero ((Fin.addCasesIter e g) i) 
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate' _ PB122) (hc ▸ this) ))

def x : Fin 2 → Ideal O := ![J0,J1] 

def x' :  Fin 2 → nonZeroDivisors (Ideal O) := by 
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (x i) (?_ )
  unfold x
  rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff (n := ![2, 2] i) (by fin_cases i <;> decide) , NPSU2.h] 
  simp only [ Submodule.zero_eq_bot, ne_eq, Ideal.span_singleton_eq_bot, NPSU2]
  fin_cases i    
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 
  · dsimp [alpha1] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide 

lemma g'_apply : ∀ (i : Fin 34), ↑(g' i) = (Fin.addCasesIter e g) i := by
  intro i
  rfl

lemma x'_apply : ∀ (i : Fin 2), ↑(x' i) = x i := by
  intro i
  rfl 
  
lemma relations_proof0 (i : Fin 10) : IsInClass O x (g 0 i) (BM 0 i) := by
  show IsInClass O x (g 0 i) (![![1, 0], ![0, 1], ![1, 1], ![1, 0], ![1, 1], ![1, 1], ![1, 0], ![1, 1], ![0, 1], ![0, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N0))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R2N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N0))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R7N0))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R7N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N0))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R17N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof1 (i : Fin 10) : IsInClass O x (g 1 i) (BM 1 i) := by
  show IsInClass O x (g 1 i) (![![1, 0], ![0, 0], ![1, 0], ![1, 0], ![1, 1], ![0, 1], ![1, 1], ![0, 0], ![1, 0], ![1, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R37N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · dsimp
    simp only [Fin.isValue, Fin.reduceFinMk, Nat.succ_eq_add_one, Nat.reduceAdd, cons_val',
    cons_val_zero, cons_val_fin_one, cons_val, cons_val_one, pow_zero, mul_one]
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R37N3))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R41N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R43N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R53N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R59N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · dsimp
    simp only [Fin.isValue, Fin.reduceFinMk, Nat.succ_eq_add_one, Nat.reduceAdd, cons_val',
    cons_val_zero, cons_val_fin_one, cons_val, cons_val_one, pow_zero, mul_one]
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R61N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R61N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof2 (i : Fin 12) : IsInClass O x (g 2 i) (BM 2 i) := by
  show IsInClass O x (g 2 i) (![![1, 0], ![1, 1], ![0, 1], ![1, 1], ![1, 1], ![1, 1], ![0, 1], ![0, 1], ![0, 1], ![1, 0], ![1, 0], ![0, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R67N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R71N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R79N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R83N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R89N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R89N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R89N3))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R97N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R101N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R101N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R103N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R103N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof3 (i : Fin 2) : IsInClass O x (g 3 i) (BM 3 i) := by
  show IsInClass O x (g 3 i) (![![0, 1], ![1, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R113N1))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R113N2))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      g'_apply x'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop g BM (IsInClass O x) ?_
    rintro ⟨i, hi⟩
    interval_cases i 
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3

def ClassGroupO_equiv : (∀ i : Fin 2 , (ZMod (![2, 2] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 2), NeZero (![2, 2] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate x'_apply NPSU2.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![2, 2] i = ∏ i, (![2] i) ^ (![2] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [2] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![2]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩ 
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases 
  by_cases h : p = 2
  simp_rw [h] ; left
  exact NPSU2 
  omega 
 
def class_group_equiv : (∀ i : Fin 2 , (ZMod (![2, 2] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_4 : NumberField.classNumber K = 4 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide 
