import IdealArithmetic.Examples.NF4_4_54381317_1.ClassGroupSaturated4_4_54381317_1_3
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F0
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F1
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F2
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F3
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F4
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F5
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F6
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F7
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F8
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F9
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F10
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F11
import IdealArithmetic.Examples.NF4_4_54381317_1.RelationIdeals4_4_54381317_1F12
import IdealArithmetic.Examples.NF4_4_54381317_1.PrimesBelowCert4_4_54381317_1
import Mathlib.NumberTheory.NumberField.ClassNumber
import IdealArithmetic.Signature.ResultantRecursive
import IdealArithmetic.DedekindProject.Discriminant
import IdealArithmetic.Generation.ClassGroupGeneration

set_option linter.all false

/- Number field `K(α)` with with α root of polynomial `X^4 - X^3 - 80*X^2 - 332*X - 383`.
Class group structure `[3, 3]`, generated by class of ideals `[(3, a - 1), (3, a + 1)]`. -/

/- Ring of integers with basis `[1, a, a^2, a^3]` -/

open BigOperators Classical Matrix Polynomial Module

noncomputable section

instance hirr : Fact $ (Irreducible (map (algebraMap ℤ ℚ) T)) where
  out :=  (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (T_monic)).1 T_irreducible

instance K_field : Field K := by
  unfold K
  exact AdjoinRoot.instField

instance K_numberField : NumberField K := by
  unfold K
  exact AdjoinRoot.instNumberFieldRat

-- These instances were not needed previously. Additional in this new Lean/Mathlib version
instance : Module ℚ K := Algebra.toModule
instance : @Algebra ℤ K CommRing.toCommSemiring CommRing.toCommSemiring.toSemiring := Ring.toIntAlgebra K
instance : @CharZero K CommRing.toCommSemiring.toNonAssocSemiring.toAddCommMonoidWithOne.toAddMonoidWithOne := charZero_of_expChar_one' K

lemma K_finrank : Module.finrank ℚ K = 4 := by
  unfold K
  erw [Module.finrank_eq_card_basis (AdjoinRoot.powerBasisAux _), Polynomial.natDegree_map_eq_of_injective, T_degree]
  · simp
  · exact RingHom.injective_int (algebraMap ℤ ℚ)
  · exact Irreducible.ne_zero hirr.out

theorem O_integral_closure : O = integralClosure ℤ K := by
  refine eq_of_piMaximal_at_all_primes_int O Om hm ?_
  intro p hp
  by_cases hc : p ∈ []
  · fin_cases hc
  · haveI : Fact $ Nat.Prime p := fact_iff.2 hp
    refine piMaximal_of_root_in_order_of_satisfiesDedekindCriterion_int Adj T_monic hm ?_ hroot_mem
     (satisfiesDedekindAlmostAllLists_of_certificate T _ T_ofList [] D p hp hc)
    rw [T_degree, rank_subalgebra_eq_card_basis Om B']


theorem  O_ringOfIntegers' : O = NumberField.RingOfIntegers K := by rw [O_integral_closure] ; rfl



instance : Module.Finite ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFiniteIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance : Module.Free ℤ (Additive ((↥O)ˣ ⧸ CommGroup.torsion (↥O)ˣ)) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFreeIntAdditiveQuotientUnitsRingOfIntegersSubgroupTorsion K

instance :  Fintype ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instFintypeSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance : IsCyclic ↥(CommGroup.torsion (↥O)ˣ) := by
  rw [O_integral_closure]
  exact NumberField.Units.instIsCyclicSubtypeUnitsRingOfIntegersMemSubgroupTorsion K

instance DD' : IsDedekindDomain O  := by
  rw [O_integral_closure]
  exact integralClosure.isDedekindDomain ℤ ℚ K

instance : Module.Free ℤ ↥O := Module.Free.of_basis B

-- Additional in this new Lean/Mathlib version
instance  : IdemCommSemiring (Ideal O) := Ideal.instIdemCommSemiring
instance : CharZero O := SubsemiringClass.instCharZero O


def SturmRC : SturmBuilderOfList [[-383, -332, -80, -1, 1], [-332, -160, -3, 4], [6460, 4144, 643], [1107673, 380140], [54381317]] [-383, -332, -80, -1, 1] [-332, -160, -3, 4] where
  hlen := by decide
  h0 := by decide
  h1 := by decide
  hlast := by decide
  hdrop := by decide
  hmono := by
    dsimp
    intro i hic
    have hi : i < 4 := by omega
    interval_cases i <;> (dsimp ; decide)
  e := [16, 413449, 144506419600]
  f := [1, 16, 413449]
  epos := by decide
  fpos := by decide
  Q := [[-1, 4], [-18505, 2572], [863066421, 244430020]]
  hel := by decide
  hfl := by decide
  hQl := by decide
  hrem := by
    dsimp
    intro i hi
    have hi : i < 3 := by omega
    interval_cases i <;> (dsimp ; decide)

def RC : RankUnitsCertificate O where
  f := X^4 - X^3 - 80*X^2 - 332*X - 383
  l := [-383, -332, -80, -1, 1]
  hl := T_ofList
  hlz := by decide
  hz := by decide
  hAdj := Adj
  heq := O_integral_closure
  P := [[-383, -332, -80, -1, 1], [-332, -160, -3, 4], [6460, 4144, 643], [1107673, 380140], [54381317]]
  SB := SturmRC
  k := 4
  r := 4
  hr := by decide
  hreq := by decide

def IC : Ideal O := Ideal.span (Set.range (fun i ↦ B.equivFun.symm (![![5, 0, 0, 0], ![2, 1, 0, 0]] i)))

def AIC: IdealEqSpanCertificate timesTableO IC
 ![![5, 0, 0, 0], ![2, 1, 0, 0]]
 ![![5, 0, 0, 0], ![2, 1, 0, 0], ![1, 0, 1, 0], ![3, 0, 0, 1]] where
  T := Table
  heq := timesTableT_eq_Table
  hieq := rfl
  M :=![![![5, 0, 0, 0], ![0, 5, 0, 0], ![0, 0, 5, 0], ![0, 0, 0, 5]], ![![2, 1, 0, 0], ![0, 2, 1, 0], ![0, 0, 2, 1], ![383, 332, 80, 3]]]
  hmulB := by decide
  f := ![![![3, 1, 6, 3], ![-5, 0, -15, 0]], ![![-2, -3, 5, 3], ![6, 5, -15, 0]], ![![-1, -1, 0, 0], ![3, 1, 0, 0]], ![![1, -1, 3, 2], ![-1, 3, -9, 0]]]
  g := ![![![1, 0, 0, 0], ![-2, 5, 0, 0], ![-1, 0, 5, 0], ![-3, 0, 0, 5]], ![![0, 1, 0, 0], ![-1, 2, 1, 0], ![-1, 0, 2, 1], ![-74, 332, 80, 3]]]
  hle1 := by decide
  hle2 := by decide

 lemma ne_dvd_torsion3 : ¬3 ∣ Nat.card ↥(CommGroup.torsion (↥O)ˣ) := by
  refine prime_not_dvd_torsion_of_not_dvd (by decide) IC
     (ideal_norm_eq_prod' B _ _ (by decide) 0 0 (by decide) (ideal_eq_of_IdealEqSpanCertificate AIC))
     (by decide) (by decide)

def NPCU3 : pMaximalUnitsCertificateNDvdT O 3 where
 hp := by decide
 r := 3
 huc := by
  erw [units_finrank_of_RankUnitsCertificate RC]
  decide
 u := ![zeta1, zeta2, zeta3]
 hu := fun i =>
  match i with
  | 0 => isUnit_zeta1
  | 1 => isUnit_zeta2
  | 2 => isUnit_zeta3
 t := 5
 hrle := by decide
 q := ![43, 43, 151, 61, 97]
 hqP := by
  intro i
  match i with
  | 0 => exact Sat3.hq43
  | 1 => exact Sat3.hq43
  | 2 => exact Sat3.hq151
  | 3 => exact Sat3.hq61
  | 4 => exact Sat3.hq97
 I := ![Sat3.I0, Sat3.I1, Sat3.I2, Sat3.I3, Sat3.I4]
 hcard := fun i =>
  match i with
  | 0 => Sat3.N0
  | 1 => Sat3.N1
  | 2 => Sat3.N2
  | 3 => Sat3.N3
  | 4 => Sat3.N4
 ζ := ![3, 3, 6, 2, 5]
 hr := fun i =>
  match i with
  | 0 => ((orderOf_of_IsOrderOf Sat3.R43) ▸ IsPrimitiveRoot.orderOf _)
  | 1 => ((orderOf_of_IsOrderOf Sat3.R43) ▸ IsPrimitiveRoot.orderOf _)
  | 2 => ((orderOf_of_IsOrderOf Sat3.R151) ▸ IsPrimitiveRoot.orderOf _)
  | 3 => ((orderOf_of_IsOrderOf Sat3.R61) ▸ IsPrimitiveRoot.orderOf _)
  | 4 => ((orderOf_of_IsOrderOf Sat3.R97) ▸ IsPrimitiveRoot.orderOf _)
 hdvd := by decide
 hpndvdt := ne_dvd_torsion3
 M := ![![0, 1, 1], ![0, 1, 2], ![2, 2, 1], ![0, 0, 0], ![0, 2, 1]]
 hM1 := by
  intro i j
  fin_cases i <;> fin_cases j
  · erw [eq_of_DiscreteLogCertificate Sat3.Log00] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log01] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log02] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log10] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log11] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log12] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log20] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log21] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log22] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log30] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log31] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log32] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log40] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log41] ; decide
  · erw [eq_of_DiscreteLogCertificate Sat3.Log42] ; decide
 Minv := ![![0, 2, 2], ![2, 2, 0], ![2, 1, 0]]
 hInv := by decide

def NPSU3 : pSaturatedClassGroupCertificateNDvdT 3 ![J0, J1] ![3, 3] where
 topMaximalUnitsCertificateNDvdT := NPCU3
 a := ![alpha0,alpha1]
 γ := 2
 hc := by decide
 ψ := ![0, 1]
 iψ := ![0, 1]
 hψ := by decide
 hψn := by
  intro i
  fin_cases i
  · decide
  · decide
 h := fun i =>
  match i with
  | 0 => by convert J0_pow3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide
  | 1 => by convert J1_pow3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide
 N := ![![0, 1], ![1, 0], ![2, 0], ![1, 1], ![0, 0]]
 hM2 := by
  intro (i : Fin 5) j
  match i , j with
  | 0, 0 => exact Sat3.Log03
  | 0, 1 => exact Sat3.Log04
  | 1, 0 => exact Sat3.Log13
  | 1, 1 => exact Sat3.Log14
  | 2, 0 => exact Sat3.Log23
  | 2, 1 => exact Sat3.Log24
  | 3, 0 => exact Sat3.Log33
  | 3, 1 => exact Sat3.Log34
  | 4, 0 => exact Sat3.Log43
  | 4, 1 => exact Sat3.Log44
 hDl := by decide
 NInv := ![![0, 2, 2, 0, 0], ![2, 2, 0, 1, 0], ![2, 2, 0, 1, 1], ![0, 1, 0, 0, 1], ![0, 2, 0, 1, 2]]
 hN := by decide

lemma T_discr : T.discr = 54381317 :=  by
  convert discriminant_eq_DiscriminantOfPRemainder_of_SturmBuilderOfList SturmRC
  rw [T_ofList]
  decide

theorem K_discr : NumberField.discr K = 54381317 := by
  rw [discr_numberField_eq_discrSubalgebraBuilder T_irreducible BQ O_integral_closure]
  rw [T_discr]
  rfl

lemma K_nrComplexPlaces : NumberField.InfinitePlace.nrComplexPlaces K = 0 := by
  rw [nrComplexPlaces_of_RankUnitsCertificate RC]
  rfl

theorem K_minowski : MinkowskiBound K ≤ (691.357086451742 : ℝ) := by
  refine K_minkowski_decimal _ ?_
  erw [K_nrComplexPlaces, K_discr, K_finrank]
  have hraux: √54381317 ≤ 7374.368931999999 := by
      refine Real.sqrt_le_iff.mpr ?_
      norm_num
  have : 3/32 * √54381317 ≤ 691.357087 := by
    refine le_trans (mul_le_mul_of_nonneg (by rfl) hraux (by norm_num) (by norm_num)) ?_
    norm_num
  norm_num
  try {linarith}


def e := ![19, 5, 2, 12, 10, 6, 8, 14, 16, 14, 6, 10, 10]
def s := ![10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 5]
def g : (i : Fin 13) → Fin (e i) → Ideal O := by
  rintro ⟨i, hi⟩
  interval_cases i
  exact ![I2N0, I3N0, I3N1, I3N2, I5N0, I5N1, I5N2, I7N0, I7N1, I11N0, I11N1, I13N0, I13N1, I17N0, I17N1, I19N0, I19N1, I23N0, I23N1]
  exact ![I43N1, I43N2, I53N1, I53N2, I61N1]
  exact ![I97N1, I97N2]
  exact ![I149N0, I149N1, I149N2, I149N3, I151N1, I151N2, I167N1, I167N2, I173N0, I173N1, I173N2, I173N3]
  exact ![I181N0, I181N1, I181N2, I181N3, I193N0, I193N1, I193N2, I193N3, I229N0, I229N1]
  exact ![I241N1, I241N2, I277N0, I277N1, I277N2, I277N3]
  exact ![I307N1, I307N2, I311N0, I311N1, I311N2, I311N3, I347N1, I347N2]
  exact ![I359N1, I359N2, I367N1, I367N2, I373N1, I373N2, I383N0, I383N2, I401N0, I401N1, I401N2, I401N3, I409N1, I409N2]
  exact ![I421N1, I421N2, I431N1, I431N2, I433N1, I433N2, I439N1, I439N2, I449N1, I449N2, I457N1, I457N2, I463N0, I463N1, I463N2, I463N3]
  exact ![I467N1, I467N2, I491N0, I491N1, I491N2, I491N3, I503N1, I503N2, I509N1, I509N2, I541N0, I541N1, I541N2, I541N3]
  exact ![I557N1, I557N2, I587N1, I587N2, I593N1, I593N2]
  exact ![I607N1, I607N2, I617N0, I617N1, I617N2, I617N3, I619N1, I619N2, I631N1, I631N2]
  exact ![I661N1, I661N2, I673N0, I673N1, I673N2, I673N3, I683N1, I683N2, I691N1, I691N2]

def BM : (i : Fin 13) → Fin (e i) → (Fin 2 → ℕ) := by
  rintro ⟨i, hi⟩
  interval_cases i
  exact ![![0, 0], ![2, 2], ![0, 1], ![1, 0], ![1, 1], ![2, 0], ![0, 2], ![2, 1], ![1, 2], ![1, 1], ![2, 2], ![2, 1], ![1, 2], ![1, 1], ![1, 1], ![2, 2], ![1, 1], ![1, 2], ![2, 1]]
  exact ![![0, 2], ![2, 0], ![1, 2], ![2, 1], ![2, 2]]
  exact ![![2, 2], ![2, 2]]
  exact ![![1, 1], ![1, 1], ![0, 1], ![1, 0], ![1, 0], ![0, 1], ![2, 0], ![0, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 2]]
  exact ![![0, 2], ![1, 0], ![0, 1], ![2, 0], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 1], ![1, 2]]
  exact ![![0, 0], ![0, 0], ![1, 0], ![0, 2], ![2, 0], ![0, 1]]
  exact ![![1, 0], ![0, 1], ![0, 1], ![0, 2], ![2, 0], ![1, 0], ![0, 0], ![0, 0]]
  exact ![![0, 0], ![0, 0], ![2, 2], ![2, 2], ![2, 0], ![0, 2], ![0, 0], ![0, 0], ![2, 0], ![0, 1], ![1, 0], ![0, 2], ![0, 1], ![1, 0]]
  exact ![![1, 0], ![0, 1], ![2, 2], ![2, 2], ![1, 1], ![1, 1], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 0], ![0, 2], ![2, 2], ![0, 2], ![2, 2], ![2, 0]]
  exact ![![0, 2], ![2, 0], ![1, 1], ![0, 1], ![1, 1], ![1, 0], ![0, 0], ![0, 0], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 1], ![1, 2]]
  exact ![![2, 0], ![0, 2], ![2, 0], ![0, 2], ![1, 2], ![2, 1]]
  exact ![![2, 1], ![1, 2], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 1], ![1, 1]]
  exact ![![1, 1], ![1, 1], ![0, 2], ![2, 0], ![1, 0], ![0, 1], ![0, 1], ![1, 0], ![2, 1], ![1, 2]]

lemma primesGenerationAux0  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 0)) => PB692.Il ((indexPair_inv s) ⟨0,x⟩))).flatten ↔ y ∈ List.ofFn (g 0) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I2N0, I3N0, I3N1, I3N2, I5N0, I5N1, I5N2, I7N0, I7N1, I11N0, I11N1, I13N0, I13N1, I17N0, I17N1, I17N1, I19N0, I19N1, I23N0, I23N1] ↔ y ∈ [I2N0, I3N0, I3N1, I3N2, I5N0, I5N1, I5N2, I7N0, I7N1, I11N0, I11N1, I13N0, I13N1, I17N0, I17N1, I19N0, I19N1, I23N0, I23N1]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux1  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 1)) => PB692.Il ((indexPair_inv s) ⟨1,x⟩))).flatten ↔ y ∈ List.ofFn (g 1) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I43N1, I43N2, I53N1, I53N2, I61N1, I61N1] ↔ y ∈ [I43N1, I43N2, I53N1, I53N2, I61N1]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux2  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 2)) => PB692.Il ((indexPair_inv s) ⟨2,x⟩))).flatten ↔ y ∈ List.ofFn (g 2) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I97N1, I97N2] ↔ y ∈ [I97N1, I97N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux3  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 3)) => PB692.Il ((indexPair_inv s) ⟨3,x⟩))).flatten ↔ y ∈ List.ofFn (g 3) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I149N0, I149N1, I149N2, I149N3, I151N1, I151N2, I167N1, I167N2, I173N0, I173N1, I173N2, I173N3] ↔ y ∈ [I149N0, I149N1, I149N2, I149N3, I151N1, I151N2, I167N1, I167N2, I173N0, I173N1, I173N2, I173N3]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux4  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 4)) => PB692.Il ((indexPair_inv s) ⟨4,x⟩))).flatten ↔ y ∈ List.ofFn (g 4) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I181N0, I181N1, I181N2, I181N3, I193N0, I193N1, I193N2, I193N3, I229N0, I229N0, I229N1, I229N1] ↔ y ∈ [I181N0, I181N1, I181N2, I181N3, I193N0, I193N1, I193N2, I193N3, I229N0, I229N1]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux5  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 5)) => PB692.Il ((indexPair_inv s) ⟨5,x⟩))).flatten ↔ y ∈ List.ofFn (g 5) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I241N1, I241N2, I277N0, I277N1, I277N2, I277N3] ↔ y ∈ [I241N1, I241N2, I277N0, I277N1, I277N2, I277N3]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux6  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 6)) => PB692.Il ((indexPair_inv s) ⟨6,x⟩))).flatten ↔ y ∈ List.ofFn (g 6) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I307N1, I307N2, I311N0, I311N1, I311N2, I311N3, I347N1, I347N2] ↔ y ∈ [I307N1, I307N2, I311N0, I311N1, I311N2, I311N3, I347N1, I347N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux7  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 7)) => PB692.Il ((indexPair_inv s) ⟨7,x⟩))).flatten ↔ y ∈ List.ofFn (g 7) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I359N1, I359N2, I367N1, I367N2, I373N1, I373N2, I383N0, I383N2, I401N0, I401N1, I401N2, I401N3, I409N1, I409N2] ↔ y ∈ [I359N1, I359N2, I367N1, I367N2, I373N1, I373N2, I383N0, I383N2, I401N0, I401N1, I401N2, I401N3, I409N1, I409N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux8  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 8)) => PB692.Il ((indexPair_inv s) ⟨8,x⟩))).flatten ↔ y ∈ List.ofFn (g 8) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I421N1, I421N2, I431N1, I431N2, I433N1, I433N2, I439N1, I439N2, I449N1, I449N2, I457N1, I457N2, I463N0, I463N1, I463N2, I463N3] ↔ y ∈ [I421N1, I421N2, I431N1, I431N2, I433N1, I433N2, I439N1, I439N2, I449N1, I449N2, I457N1, I457N2, I463N0, I463N1, I463N2, I463N3]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux9  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 9)) => PB692.Il ((indexPair_inv s) ⟨9,x⟩))).flatten ↔ y ∈ List.ofFn (g 9) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I467N1, I467N2, I491N0, I491N1, I491N2, I491N3, I503N1, I503N2, I509N1, I509N2, I541N0, I541N1, I541N2, I541N3] ↔ y ∈ [I467N1, I467N2, I491N0, I491N1, I491N2, I491N3, I503N1, I503N2, I509N1, I509N2, I541N0, I541N1, I541N2, I541N3]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux10  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 10)) => PB692.Il ((indexPair_inv s) ⟨10,x⟩))).flatten ↔ y ∈ List.ofFn (g 10) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I557N1, I557N2, I587N1, I587N2, I593N1, I593N2] ↔ y ∈ [I557N1, I557N2, I587N1, I587N2, I593N1, I593N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux11  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 11)) => PB692.Il ((indexPair_inv s) ⟨11,x⟩))).flatten ↔ y ∈ List.ofFn (g 11) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I607N1, I607N2, I617N0, I617N1, I617N2, I617N3, I619N1, I619N2, I631N1, I631N2] ↔ y ∈ [I607N1, I607N2, I617N0, I617N1, I617N2, I617N3, I619N1, I619N2, I631N1, I631N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux12  {y} :
    y ∈ (List.ofFn (fun (x : Fin (s 12)) => PB692.Il ((indexPair_inv s) ⟨12,x⟩))).flatten ↔ y ∈ List.ofFn (g 12) := by
  erw [ primesBelowBoundCertificate_of_Interval_Il_apply' _ (by decide)]
  show y ∈ [I661N1, I661N2, I673N0, I673N1, I673N2, I673N3, I683N1, I683N2, I691N1, I691N2] ↔ y ∈ [I661N1, I661N2, I673N0, I673N1, I673N2, I673N3, I683N1, I683N2, I691N1, I691N2]
  simp only [List.mem_cons, List.not_mem_nil, or_false, or_self, or_self_left]


lemma primesGenerationAux {x} : x ∈ (List.ofFn PB692.Il).flatten ↔ x ∈ List.ofFn (Fin.addCasesIter e g) := by
  refine (list_flatten_eq_list_addCasesIter g (s := s) PB692.Il ?_ x)
  rintro ⟨i, hi⟩ x
  interval_cases i
  · exact primesGenerationAux0
  · exact primesGenerationAux1
  · exact primesGenerationAux2
  · exact primesGenerationAux3
  · exact primesGenerationAux4
  · exact primesGenerationAux5
  · exact primesGenerationAux6
  · exact primesGenerationAux7
  · exact primesGenerationAux8
  · exact primesGenerationAux9
  · exact primesGenerationAux10
  · exact primesGenerationAux11
  · exact primesGenerationAux12

lemma primesGenerationBelow : {I : Ideal O | 0 < I.absNorm ∧ I.IsPrime ∧ I.absNorm < 692} ⊆ Set.range (Fin.addCasesIter e g) :=
  le_primes_below_bound_of_PrimesBelowBoundCertificate_le' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv ((Fin.addCasesIter e g)) PB692 (fun _ hx => primesGenerationAux.1 hx)

def g' : Fin 132 → nonZeroDivisors (Ideal O) := by
  intro i
  have : (Fin.addCasesIter e g) i ∈ (List.ofFn PB692.Il).flatten := by
    simp only [primesGenerationAux, List.mem_ofFn, exists_apply_eq_apply]
  exact Ideal.toNonZeroDivisorOfNeZero ((Fin.addCasesIter e g) i)
    (fun hc => ((zero_ne_mem_of_PrimesBelowCertificate' _ PB692) (hc ▸ this) ))

def x : Fin 2 → Ideal O := ![J0,J1]

def x' :  Fin 2 → nonZeroDivisors (Ideal O) := by
  refine fun i => Ideal.toNonZeroDivisorOfNeZero (x i) (?_ )
  -- v4.32: the old `rw [← Submodule.zero_eq_bot, ← pow_ne_zero_iff …]` no longer
  -- fires (two distinct `Zero (Ideal O)` instances: `⊥` vs the `MonoidWithZero` 0).
  -- Argue by contradiction: if `xᵢ = ⊥` then `xᵢ ^ nᵢ ≤ ⊥`, but the certificate says
  -- `xᵢ ^ nᵢ` is a nonzero principal ideal.
  intro hc
  have hle : x i ^ ![3, 3] i = ⊥ :=
    le_bot_iff.mp ((Ideal.pow_le_self (by fin_cases i <;> decide)).trans hc.le)
  rw [show x i ^ ![3, 3] i = _ from NPSU3.h i] at hle
  revert hle
  simp only [imp_false, ne_eq, Ideal.span_singleton_eq_bot, NPSU3]
  fin_cases i
  · dsimp [alpha0] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide
  · dsimp [alpha1] ; rw [(LinearEquiv.map_eq_zero_iff B.equivFun.symm)] ; decide

lemma g'_apply : ∀ (i : Fin 132), ↑(g' i) = (Fin.addCasesIter e g) i := by
  intro i
  rfl

lemma x'_apply : ∀ (i : Fin 2), ↑(x' i) = x i := by
  intro i
  rfl

/-- v4.32 helper. Proven in a clean *generic* `[CommRing A]` context, where `simp`
reduces the all-`^0` product to `1`. Inside this file the local instances stop
`simp`/`rw` from firing `pow_zero`/`mul_one` on the goal's product directly, so the
all-zero-exponent `IsInClass` bullets multiply through this instead (matched by
`Eq.trans` up to defeq). -/
private lemma span_eq_span_mul_prod_zero₂ {A : Type*} [CommRing A] (β : A) (a b : Ideal A) :
    Ideal.span {β} = Ideal.span {β} * (1 * a ^ 0 * b ^ 0) := by simp

lemma relations_proof0 (i : Fin 19) : IsInClass O x (g 0 i) (BM 0 i) := by
  show IsInClass O x (g 0 i) (![![0, 0], ![2, 2], ![0, 1], ![1, 0], ![1, 1], ![2, 0], ![0, 2], ![2, 1], ![1, 2], ![1, 1], ![2, 2], ![2, 1], ![1, 2], ![1, 1], ![1, 1], ![2, 2], ![1, 1], ![1, 2], ![2, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨0,_⟩ : Fin (e 0)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 0 ((fun i ↦ i) ⟨0, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R3N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R5N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R7N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R7N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R11N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R13N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R13N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R17N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R17N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R19N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R19N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R23N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R23N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof1 (i : Fin 5) : IsInClass O x (g 1 i) (BM 1 i) := by
  show IsInClass O x (g 1 i) (![![0, 2], ![2, 0], ![1, 2], ![2, 1], ![2, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R43N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R43N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R53N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R53N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R61N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof2 (i : Fin 2) : IsInClass O x (g 2 i) (BM 2 i) := by
  show IsInClass O x (g 2 i) (![![2, 2], ![2, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R97N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R97N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof3 (i : Fin 12) : IsInClass O x (g 3 i) (BM 3 i) := by
  show IsInClass O x (g 3 i) (![![1, 1], ![1, 1], ![0, 1], ![1, 0], ![1, 0], ![0, 1], ![2, 0], ![0, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R149N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R149N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R149N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R149N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R151N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R151N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R167N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R167N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R173N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R173N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R173N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R173N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof4 (i : Fin 10) : IsInClass O x (g 4 i) (BM 4 i) := by
  show IsInClass O x (g 4 i) (![![0, 2], ![1, 0], ![0, 1], ![2, 0], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 1], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R181N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R181N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R181N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R181N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R193N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R193N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R193N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R193N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R229N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R229N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof5 (i : Fin 6) : IsInClass O x (g 5 i) (BM 5 i) := by
  show IsInClass O x (g 5 i) (![![0, 0], ![0, 0], ![1, 0], ![0, 2], ![2, 0], ![0, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨0,_⟩ : Fin (e 5)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 5 ((fun i ↦ i) ⟨0, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨1,_⟩ : Fin (e 5)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 5 ((fun i ↦ i) ⟨1, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R277N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R277N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R277N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R277N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof6 (i : Fin 8) : IsInClass O x (g 6 i) (BM 6 i) := by
  show IsInClass O x (g 6 i) (![![1, 0], ![0, 1], ![0, 1], ![0, 2], ![2, 0], ![1, 0], ![0, 0], ![0, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R307N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R307N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R311N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R311N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R311N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R311N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨6,_⟩ : Fin (e 6)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 6 ((fun i ↦ i) ⟨6, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨7,_⟩ : Fin (e 6)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 6 ((fun i ↦ i) ⟨7, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl

lemma relations_proof7 (i : Fin 14) : IsInClass O x (g 7 i) (BM 7 i) := by
  show IsInClass O x (g 7 i) (![![0, 0], ![0, 0], ![2, 2], ![2, 2], ![2, 0], ![0, 2], ![0, 0], ![0, 0], ![2, 0], ![0, 1], ![1, 0], ![0, 2], ![0, 1], ![1, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨0,_⟩ : Fin (e 7)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 7 ((fun i ↦ i) ⟨0, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨1,_⟩ : Fin (e 7)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 7 ((fun i ↦ i) ⟨1, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R367N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R367N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R373N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R373N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨6,_⟩ : Fin (e 7)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 7 ((fun i ↦ i) ⟨6, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨7,_⟩ : Fin (e 7)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 7 ((fun i ↦ i) ⟨7, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R401N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R401N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R401N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R401N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R409N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R409N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof8 (i : Fin 16) : IsInClass O x (g 8 i) (BM 8 i) := by
  show IsInClass O x (g 8 i) (![![1, 0], ![0, 1], ![2, 2], ![2, 2], ![1, 1], ![1, 1], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 0], ![0, 2], ![2, 2], ![0, 2], ![2, 2], ![2, 0]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R421N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R421N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R431N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R431N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R433N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R433N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R439N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R439N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R449N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R449N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R457N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R457N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R463N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R463N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R463N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R463N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof9 (i : Fin 14) : IsInClass O x (g 9 i) (BM 9 i) := by
  show IsInClass O x (g 9 i) (![![0, 2], ![2, 0], ![1, 1], ![0, 1], ![1, 1], ![1, 0], ![0, 0], ![0, 0], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![2, 1], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R467N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R467N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R491N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R491N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R491N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R491N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨6,_⟩ : Fin (e 9)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 9 ((fun i ↦ i) ⟨6, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · -- v4.32: `ideal_mem_principal_class''` needs `v` pinned; the opaque `g`/`e`/`BM` leave
    -- the index `⟨7,_⟩ : Fin (e 9)` stuck, so restate via `suffices` (its `= span {b}`
    -- conclusion pins `v`) and bridge the all-`^0` product through the generic helper.
    suffices h : ∃ a b : ↑O, ∃ (_ : a ≠ 0) (_ : b ≠ 0),
        Ideal.span {a} * g 9 ((fun i ↦ i) ⟨7, by decide⟩) = Ideal.span {b} by
      obtain ⟨a, b, ha, hb, hab⟩ := h
      exact ⟨a, b, ha, hb, hab.trans (span_eq_span_mul_prod_zero₂ b (x 0) (x 1))⟩
    exact ideal_mem_principal_class'' B _ _ (by decide) rfl
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R509N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R509N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R541N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R541N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R541N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R541N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof10 (i : Fin 6) : IsInClass O x (g 10 i) (BM 10 i) := by
  show IsInClass O x (g 10 i) (![![2, 0], ![0, 2], ![2, 0], ![0, 2], ![1, 2], ![2, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R557N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R557N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R587N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R587N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R593N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R593N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof11 (i : Fin 10) : IsInClass O x (g 11 i) (BM 11 i) := by
  show IsInClass O x (g 11 i) (![![2, 1], ![1, 2], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 2], ![2, 1], ![1, 1], ![1, 1]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R607N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R607N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R617N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R617N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R617N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R617N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R619N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R619N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R631N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R631N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

lemma relations_proof12 (i : Fin 10) : IsInClass O x (g 12 i) (BM 12 i) := by
  show IsInClass O x (g 12 i) (![![1, 1], ![1, 1], ![0, 2], ![2, 0], ![1, 0], ![0, 1], ![0, 1], ![1, 0], ![2, 1], ![1, 2]] i)
  unfold IsInClass
  simp only [Fin.isValue, Fin.prod_univ_castSucc, Finset.univ_eq_empty, Finset.prod_empty, Fin.succ_zero_eq_one, one_mul]
  dsimp
  fin_cases i
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R661N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R661N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R673N0 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R673N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R673N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R673N3 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R683N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R683N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R691N1 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)
  · refine Exists.intro _ (Exists.intro ?_ (Exists.intro (?_) (Exists.intro ?_ (by convert R691N2 <;> first | rfl | (simp [BM, g, x]; done) | (simp; done) | decide))))
    refine Nat.cast_ne_zero.2 (by decide)
    exact (LinearEquiv.map_ne_zero_iff B.equivFun.symm).mpr (by decide)

theorem class_group_generator : Subgroup.closure (Set.range (fun i => ClassGroup.mk0 (x' i))) = ⊤ := by
  refine subgroup_closure_eq_classGroup'' (Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv
      g'_apply x'_apply ?_ primesGenerationBelow (Fin.addCasesIter e BM) ?_
  · refine lt_of_le_of_lt K_minowski ?_
    norm_num
  · refine forall_addCasesIter_prop g BM (IsInClass O x) ?_
    rintro ⟨i, hi⟩
    interval_cases i
    · exact relations_proof0
    · exact relations_proof1
    · exact relations_proof2
    · exact relations_proof3
    · exact relations_proof4
    · exact relations_proof5
    · exact relations_proof6
    · exact relations_proof7
    · exact relations_proof8
    · exact relations_proof9
    · exact relations_proof10
    · exact relations_proof11
    · exact relations_proof12

def ClassGroupO_equiv : (∀ i : Fin 2 , (ZMod (![3, 3] i))) ≃+ Additive (ClassGroup O) := by
  haveI : ∀ (i : Fin 2), NeZero (![3, 3] i) := by
    intro i
    fin_cases i <;>  exact {out := by decide}
  refine ClassGroup_equiv_of_pSaturatedCertificate x'_apply NPSU3.h class_group_generator ?_
  rintro ⟨p, hp1, hp2⟩
  have : ∏ i, ![3, 3] i = ∏ i, (![3] i) ^ (![2] i)  := by decide
  rw [this] at hp2
  have hp_cases : p ∈ [3] := by
    obtain ⟨j ,hj1, hj2⟩  := Prime.exists_mem_finset_dvd (Nat.prime_iff.mp hp1) hp2
    show p ∈ List.ofFn ![3]
    rw [(Nat.prime_dvd_prime_iff_eq hp1 ?_).1 (Nat.Prime.dvd_of_dvd_pow hp1 hj2), List.mem_ofFn]
    exact ⟨j, rfl⟩
    fin_cases j <;> decide
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hp_cases
  by_cases h : p = 3
  simp_rw [h] ; right
  exact NPSU3
  omega

def class_group_equiv : (∀ i : Fin 2 , (ZMod (![3, 3] i))) ≃+ Additive (ClassGroup (NumberField.RingOfIntegers K)) := by
 refine AddEquiv.trans ClassGroupO_equiv ?_
 exact MulEquiv.toAdditive (ClassGroup.congr
    ((Subalgebra.equivOfEq _ _ O_integral_closure).toRingEquiv))

theorem class_number_K_eq_9 : NumberField.classNumber K = 9 := by
  unfold NumberField.classNumber
  rw [Fintype.card_eq_nat_card, ← Nat.card_congr (Additive.toMul),
    Nat.card_congr (class_group_equiv).symm.toEquiv, Nat.card_pi]
  simp [Fin.isValue, Fin.prod_succ]
  try decide
